version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/release/go"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/release/openapi/swagger"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
