// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacemesh/v1/smesher_types.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Bit flags for compute engine selection
type ComputeEngineFlag int32

const (
	ComputeEngineFlag_COMPUTE_ENGINE_FLAG_UNSPECIFIED ComputeEngineFlag = 0
	ComputeEngineFlag_COMPUTE_ENGINE_FLAG_CPU         ComputeEngineFlag = 1
	ComputeEngineFlag_COMPUTE_ENGINE_FLAG_CUDA        ComputeEngineFlag = 2
	ComputeEngineFlag_COMPUTE_ENGINE_FLAG_VULKAN      ComputeEngineFlag = 4
)

var ComputeEngineFlag_name = map[int32]string{
	0: "COMPUTE_ENGINE_FLAG_UNSPECIFIED",
	1: "COMPUTE_ENGINE_FLAG_CPU",
	2: "COMPUTE_ENGINE_FLAG_CUDA",
	4: "COMPUTE_ENGINE_FLAG_VULKAN",
}

var ComputeEngineFlag_value = map[string]int32{
	"COMPUTE_ENGINE_FLAG_UNSPECIFIED": 0,
	"COMPUTE_ENGINE_FLAG_CPU":         1,
	"COMPUTE_ENGINE_FLAG_CUDA":        2,
	"COMPUTE_ENGINE_FLAG_VULKAN":      4,
}

func (x ComputeEngineFlag) String() string {
	return proto.EnumName(ComputeEngineFlag_name, int32(x))
}

func (ComputeEngineFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{0}
}

type PostStatus_FilesStatus int32

const (
	PostStatus_FILES_STATUS_UNSPECIFIED PostStatus_FilesStatus = 0
	PostStatus_FILES_STATUS_NOT_FOUND   PostStatus_FilesStatus = 1
	PostStatus_FILES_STATUS_PARTIAL     PostStatus_FilesStatus = 2
	PostStatus_FILES_STATUS_COMPLETE    PostStatus_FilesStatus = 3
)

var PostStatus_FilesStatus_name = map[int32]string{
	0: "FILES_STATUS_UNSPECIFIED",
	1: "FILES_STATUS_NOT_FOUND",
	2: "FILES_STATUS_PARTIAL",
	3: "FILES_STATUS_COMPLETE",
}

var PostStatus_FilesStatus_value = map[string]int32{
	"FILES_STATUS_UNSPECIFIED": 0,
	"FILES_STATUS_NOT_FOUND":   1,
	"FILES_STATUS_PARTIAL":     2,
	"FILES_STATUS_COMPLETE":    3,
}

func (x PostStatus_FilesStatus) String() string {
	return proto.EnumName(PostStatus_FilesStatus_name, int32(x))
}

func (PostStatus_FilesStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{18, 0}
}

type PostStatus_ErrorType int32

const (
	PostStatus_ERROR_TYPE_UNSPECIFIED    PostStatus_ErrorType = 0
	PostStatus_ERROR_TYPE_FILE_NOT_FOUND PostStatus_ErrorType = 1
	PostStatus_ERROR_TYPE_READ_ERROR     PostStatus_ErrorType = 2
	PostStatus_ERROR_TYPE_WRITE_ERROR    PostStatus_ErrorType = 3
)

var PostStatus_ErrorType_name = map[int32]string{
	0: "ERROR_TYPE_UNSPECIFIED",
	1: "ERROR_TYPE_FILE_NOT_FOUND",
	2: "ERROR_TYPE_READ_ERROR",
	3: "ERROR_TYPE_WRITE_ERROR",
}

var PostStatus_ErrorType_value = map[string]int32{
	"ERROR_TYPE_UNSPECIFIED":    0,
	"ERROR_TYPE_FILE_NOT_FOUND": 1,
	"ERROR_TYPE_READ_ERROR":     2,
	"ERROR_TYPE_WRITE_ERROR":    3,
}

func (x PostStatus_ErrorType) String() string {
	return proto.EnumName(PostStatus_ErrorType_name, int32(x))
}

func (PostStatus_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{18, 1}
}

type IsSmeshingResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IsSmeshingResponse) Reset()         { *m = IsSmeshingResponse{} }
func (m *IsSmeshingResponse) String() string { return proto.CompactTextString(m) }
func (*IsSmeshingResponse) ProtoMessage()    {}
func (*IsSmeshingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{0}
}

func (m *IsSmeshingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsSmeshingResponse.Unmarshal(m, b)
}
func (m *IsSmeshingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsSmeshingResponse.Marshal(b, m, deterministic)
}
func (m *IsSmeshingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsSmeshingResponse.Merge(m, src)
}
func (m *IsSmeshingResponse) XXX_Size() int {
	return xxx_messageInfo_IsSmeshingResponse.Size(m)
}
func (m *IsSmeshingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsSmeshingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsSmeshingResponse proto.InternalMessageInfo

func (m *IsSmeshingResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StartSmeshingResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StartSmeshingResponse) Reset()         { *m = StartSmeshingResponse{} }
func (m *StartSmeshingResponse) String() string { return proto.CompactTextString(m) }
func (*StartSmeshingResponse) ProtoMessage()    {}
func (*StartSmeshingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{1}
}

func (m *StartSmeshingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSmeshingResponse.Unmarshal(m, b)
}
func (m *StartSmeshingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSmeshingResponse.Marshal(b, m, deterministic)
}
func (m *StartSmeshingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSmeshingResponse.Merge(m, src)
}
func (m *StartSmeshingResponse) XXX_Size() int {
	return xxx_messageInfo_StartSmeshingResponse.Size(m)
}
func (m *StartSmeshingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSmeshingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartSmeshingResponse proto.InternalMessageInfo

func (m *StartSmeshingResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StopSmeshingResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StopSmeshingResponse) Reset()         { *m = StopSmeshingResponse{} }
func (m *StopSmeshingResponse) String() string { return proto.CompactTextString(m) }
func (*StopSmeshingResponse) ProtoMessage()    {}
func (*StopSmeshingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{2}
}

func (m *StopSmeshingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSmeshingResponse.Unmarshal(m, b)
}
func (m *StopSmeshingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSmeshingResponse.Marshal(b, m, deterministic)
}
func (m *StopSmeshingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSmeshingResponse.Merge(m, src)
}
func (m *StopSmeshingResponse) XXX_Size() int {
	return xxx_messageInfo_StopSmeshingResponse.Size(m)
}
func (m *StopSmeshingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSmeshingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopSmeshingResponse proto.InternalMessageInfo

func (m *StopSmeshingResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetCoinbaseRequest struct {
	Id                   *AccountId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetCoinbaseRequest) Reset()         { *m = SetCoinbaseRequest{} }
func (m *SetCoinbaseRequest) String() string { return proto.CompactTextString(m) }
func (*SetCoinbaseRequest) ProtoMessage()    {}
func (*SetCoinbaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{3}
}

func (m *SetCoinbaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCoinbaseRequest.Unmarshal(m, b)
}
func (m *SetCoinbaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCoinbaseRequest.Marshal(b, m, deterministic)
}
func (m *SetCoinbaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCoinbaseRequest.Merge(m, src)
}
func (m *SetCoinbaseRequest) XXX_Size() int {
	return xxx_messageInfo_SetCoinbaseRequest.Size(m)
}
func (m *SetCoinbaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCoinbaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCoinbaseRequest proto.InternalMessageInfo

func (m *SetCoinbaseRequest) GetId() *AccountId {
	if m != nil {
		return m.Id
	}
	return nil
}

type SetCoinbaseResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetCoinbaseResponse) Reset()         { *m = SetCoinbaseResponse{} }
func (m *SetCoinbaseResponse) String() string { return proto.CompactTextString(m) }
func (*SetCoinbaseResponse) ProtoMessage()    {}
func (*SetCoinbaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{4}
}

func (m *SetCoinbaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCoinbaseResponse.Unmarshal(m, b)
}
func (m *SetCoinbaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCoinbaseResponse.Marshal(b, m, deterministic)
}
func (m *SetCoinbaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCoinbaseResponse.Merge(m, src)
}
func (m *SetCoinbaseResponse) XXX_Size() int {
	return xxx_messageInfo_SetCoinbaseResponse.Size(m)
}
func (m *SetCoinbaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCoinbaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCoinbaseResponse proto.InternalMessageInfo

func (m *SetCoinbaseResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type MinGasResponse struct {
	Mingas               *SimpleInt `protobuf:"bytes,1,opt,name=mingas,proto3" json:"mingas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MinGasResponse) Reset()         { *m = MinGasResponse{} }
func (m *MinGasResponse) String() string { return proto.CompactTextString(m) }
func (*MinGasResponse) ProtoMessage()    {}
func (*MinGasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{5}
}

func (m *MinGasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinGasResponse.Unmarshal(m, b)
}
func (m *MinGasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinGasResponse.Marshal(b, m, deterministic)
}
func (m *MinGasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinGasResponse.Merge(m, src)
}
func (m *MinGasResponse) XXX_Size() int {
	return xxx_messageInfo_MinGasResponse.Size(m)
}
func (m *MinGasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinGasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinGasResponse proto.InternalMessageInfo

func (m *MinGasResponse) GetMingas() *SimpleInt {
	if m != nil {
		return m.Mingas
	}
	return nil
}

type SetMinGasRequest struct {
	Mingas               *SimpleInt `protobuf:"bytes,1,opt,name=mingas,proto3" json:"mingas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetMinGasRequest) Reset()         { *m = SetMinGasRequest{} }
func (m *SetMinGasRequest) String() string { return proto.CompactTextString(m) }
func (*SetMinGasRequest) ProtoMessage()    {}
func (*SetMinGasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{6}
}

func (m *SetMinGasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMinGasRequest.Unmarshal(m, b)
}
func (m *SetMinGasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMinGasRequest.Marshal(b, m, deterministic)
}
func (m *SetMinGasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMinGasRequest.Merge(m, src)
}
func (m *SetMinGasRequest) XXX_Size() int {
	return xxx_messageInfo_SetMinGasRequest.Size(m)
}
func (m *SetMinGasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMinGasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMinGasRequest proto.InternalMessageInfo

func (m *SetMinGasRequest) GetMingas() *SimpleInt {
	if m != nil {
		return m.Mingas
	}
	return nil
}

type SetMinGasResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetMinGasResponse) Reset()         { *m = SetMinGasResponse{} }
func (m *SetMinGasResponse) String() string { return proto.CompactTextString(m) }
func (*SetMinGasResponse) ProtoMessage()    {}
func (*SetMinGasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{7}
}

func (m *SetMinGasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMinGasResponse.Unmarshal(m, b)
}
func (m *SetMinGasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMinGasResponse.Marshal(b, m, deterministic)
}
func (m *SetMinGasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMinGasResponse.Merge(m, src)
}
func (m *SetMinGasResponse) XXX_Size() int {
	return xxx_messageInfo_SetMinGasResponse.Size(m)
}
func (m *SetMinGasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMinGasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMinGasResponse proto.InternalMessageInfo

func (m *SetMinGasResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreatePostDataResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreatePostDataResponse) Reset()         { *m = CreatePostDataResponse{} }
func (m *CreatePostDataResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostDataResponse) ProtoMessage()    {}
func (*CreatePostDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{8}
}

func (m *CreatePostDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostDataResponse.Unmarshal(m, b)
}
func (m *CreatePostDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostDataResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostDataResponse.Merge(m, src)
}
func (m *CreatePostDataResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostDataResponse.Size(m)
}
func (m *CreatePostDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostDataResponse proto.InternalMessageInfo

func (m *CreatePostDataResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StopPostDataCreationSessionResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StopPostDataCreationSessionResponse) Reset()         { *m = StopPostDataCreationSessionResponse{} }
func (m *StopPostDataCreationSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StopPostDataCreationSessionResponse) ProtoMessage()    {}
func (*StopPostDataCreationSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{9}
}

func (m *StopPostDataCreationSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPostDataCreationSessionResponse.Unmarshal(m, b)
}
func (m *StopPostDataCreationSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPostDataCreationSessionResponse.Marshal(b, m, deterministic)
}
func (m *StopPostDataCreationSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPostDataCreationSessionResponse.Merge(m, src)
}
func (m *StopPostDataCreationSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StopPostDataCreationSessionResponse.Size(m)
}
func (m *StopPostDataCreationSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPostDataCreationSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopPostDataCreationSessionResponse proto.InternalMessageInfo

func (m *StopPostDataCreationSessionResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SmesherIdResponse struct {
	AccountId            *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SmesherIdResponse) Reset()         { *m = SmesherIdResponse{} }
func (m *SmesherIdResponse) String() string { return proto.CompactTextString(m) }
func (*SmesherIdResponse) ProtoMessage()    {}
func (*SmesherIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{10}
}

func (m *SmesherIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmesherIdResponse.Unmarshal(m, b)
}
func (m *SmesherIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmesherIdResponse.Marshal(b, m, deterministic)
}
func (m *SmesherIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmesherIdResponse.Merge(m, src)
}
func (m *SmesherIdResponse) XXX_Size() int {
	return xxx_messageInfo_SmesherIdResponse.Size(m)
}
func (m *SmesherIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmesherIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmesherIdResponse proto.InternalMessageInfo

func (m *SmesherIdResponse) GetAccountId() *AccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type CoinbaseResponse struct {
	AccountId            *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CoinbaseResponse) Reset()         { *m = CoinbaseResponse{} }
func (m *CoinbaseResponse) String() string { return proto.CompactTextString(m) }
func (*CoinbaseResponse) ProtoMessage()    {}
func (*CoinbaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{11}
}

func (m *CoinbaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinbaseResponse.Unmarshal(m, b)
}
func (m *CoinbaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinbaseResponse.Marshal(b, m, deterministic)
}
func (m *CoinbaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinbaseResponse.Merge(m, src)
}
func (m *CoinbaseResponse) XXX_Size() int {
	return xxx_messageInfo_CoinbaseResponse.Size(m)
}
func (m *CoinbaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinbaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinbaseResponse proto.InternalMessageInfo

func (m *CoinbaseResponse) GetAccountId() *AccountId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type ComputeEngineFlags struct {
	ComputeEngineFlags   uint32   `protobuf:"varint,1,opt,name=compute_engine_flags,json=computeEngineFlags,proto3" json:"compute_engine_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeEngineFlags) Reset()         { *m = ComputeEngineFlags{} }
func (m *ComputeEngineFlags) String() string { return proto.CompactTextString(m) }
func (*ComputeEngineFlags) ProtoMessage()    {}
func (*ComputeEngineFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{12}
}

func (m *ComputeEngineFlags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeEngineFlags.Unmarshal(m, b)
}
func (m *ComputeEngineFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeEngineFlags.Marshal(b, m, deterministic)
}
func (m *ComputeEngineFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeEngineFlags.Merge(m, src)
}
func (m *ComputeEngineFlags) XXX_Size() int {
	return xxx_messageInfo_ComputeEngineFlags.Size(m)
}
func (m *ComputeEngineFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeEngineFlags.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeEngineFlags proto.InternalMessageInfo

func (m *ComputeEngineFlags) GetComputeEngineFlags() uint32 {
	if m != nil {
		return m.ComputeEngineFlags
	}
	return 0
}

type AvailableComputeEnginesResponse struct {
	Flags                *ComputeEngineFlags `protobuf:"bytes,1,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AvailableComputeEnginesResponse) Reset()         { *m = AvailableComputeEnginesResponse{} }
func (m *AvailableComputeEnginesResponse) String() string { return proto.CompactTextString(m) }
func (*AvailableComputeEnginesResponse) ProtoMessage()    {}
func (*AvailableComputeEnginesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{13}
}

func (m *AvailableComputeEnginesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableComputeEnginesResponse.Unmarshal(m, b)
}
func (m *AvailableComputeEnginesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableComputeEnginesResponse.Marshal(b, m, deterministic)
}
func (m *AvailableComputeEnginesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableComputeEnginesResponse.Merge(m, src)
}
func (m *AvailableComputeEnginesResponse) XXX_Size() int {
	return xxx_messageInfo_AvailableComputeEnginesResponse.Size(m)
}
func (m *AvailableComputeEnginesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableComputeEnginesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableComputeEnginesResponse proto.InternalMessageInfo

func (m *AvailableComputeEnginesResponse) GetFlags() *ComputeEngineFlags {
	if m != nil {
		return m.Flags
	}
	return nil
}

// Basic post data. Used for users to provide requested post data and by
// other messages which contain post data.
type PostData struct {
	Path                 string              `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DataSize             uint64              `protobuf:"varint,2,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	Append               bool                `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	Throttle             bool                `protobuf:"varint,4,opt,name=throttle,proto3" json:"throttle,omitempty"`
	ComputeEngineFlags   *ComputeEngineFlags `protobuf:"bytes,5,opt,name=compute_engine_flags,json=computeEngineFlags,proto3" json:"compute_engine_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PostData) Reset()         { *m = PostData{} }
func (m *PostData) String() string { return proto.CompactTextString(m) }
func (*PostData) ProtoMessage()    {}
func (*PostData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{14}
}

func (m *PostData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostData.Unmarshal(m, b)
}
func (m *PostData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostData.Marshal(b, m, deterministic)
}
func (m *PostData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostData.Merge(m, src)
}
func (m *PostData) XXX_Size() int {
	return xxx_messageInfo_PostData.Size(m)
}
func (m *PostData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostData.DiscardUnknown(m)
}

var xxx_messageInfo_PostData proto.InternalMessageInfo

func (m *PostData) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PostData) GetDataSize() uint64 {
	if m != nil {
		return m.DataSize
	}
	return 0
}

func (m *PostData) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

func (m *PostData) GetThrottle() bool {
	if m != nil {
		return m.Throttle
	}
	return false
}

func (m *PostData) GetComputeEngineFlags() *ComputeEngineFlags {
	if m != nil {
		return m.ComputeEngineFlags
	}
	return nil
}

type CreatePostDataRequest struct {
	Data                 *PostData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePostDataRequest) Reset()         { *m = CreatePostDataRequest{} }
func (m *CreatePostDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostDataRequest) ProtoMessage()    {}
func (*CreatePostDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{15}
}

func (m *CreatePostDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostDataRequest.Unmarshal(m, b)
}
func (m *CreatePostDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostDataRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostDataRequest.Merge(m, src)
}
func (m *CreatePostDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostDataRequest.Size(m)
}
func (m *CreatePostDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostDataRequest proto.InternalMessageInfo

func (m *CreatePostDataRequest) GetData() *PostData {
	if m != nil {
		return m.Data
	}
	return nil
}

// Param passed to methods to indicate a request to delete data files
type StopSmeshingRequest struct {
	DeleteFiles          bool     `protobuf:"varint,1,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSmeshingRequest) Reset()         { *m = StopSmeshingRequest{} }
func (m *StopSmeshingRequest) String() string { return proto.CompactTextString(m) }
func (*StopSmeshingRequest) ProtoMessage()    {}
func (*StopSmeshingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{16}
}

func (m *StopSmeshingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSmeshingRequest.Unmarshal(m, b)
}
func (m *StopSmeshingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSmeshingRequest.Marshal(b, m, deterministic)
}
func (m *StopSmeshingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSmeshingRequest.Merge(m, src)
}
func (m *StopSmeshingRequest) XXX_Size() int {
	return xxx_messageInfo_StopSmeshingRequest.Size(m)
}
func (m *StopSmeshingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSmeshingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopSmeshingRequest proto.InternalMessageInfo

func (m *StopSmeshingRequest) GetDeleteFiles() bool {
	if m != nil {
		return m.DeleteFiles
	}
	return false
}

type StopPostDataCreationSessionRequest struct {
	DeleteFiles          bool     `protobuf:"varint,1,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopPostDataCreationSessionRequest) Reset()         { *m = StopPostDataCreationSessionRequest{} }
func (m *StopPostDataCreationSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StopPostDataCreationSessionRequest) ProtoMessage()    {}
func (*StopPostDataCreationSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{17}
}

func (m *StopPostDataCreationSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPostDataCreationSessionRequest.Unmarshal(m, b)
}
func (m *StopPostDataCreationSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPostDataCreationSessionRequest.Marshal(b, m, deterministic)
}
func (m *StopPostDataCreationSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPostDataCreationSessionRequest.Merge(m, src)
}
func (m *StopPostDataCreationSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StopPostDataCreationSessionRequest.Size(m)
}
func (m *StopPostDataCreationSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPostDataCreationSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopPostDataCreationSessionRequest proto.InternalMessageInfo

func (m *StopPostDataCreationSessionRequest) GetDeleteFiles() bool {
	if m != nil {
		return m.DeleteFiles
	}
	return false
}

// Proof of space data status
type PostStatus struct {
	PostData             *PostData              `protobuf:"bytes,1,opt,name=post_data,json=postData,proto3" json:"post_data,omitempty"`
	FilesStatus          PostStatus_FilesStatus `protobuf:"varint,2,opt,name=files_status,json=filesStatus,proto3,enum=spacemesh.v1.PostStatus_FilesStatus" json:"files_status,omitempty"`
	InitInProgress       bool                   `protobuf:"varint,3,opt,name=init_in_progress,json=initInProgress,proto3" json:"init_in_progress,omitempty"`
	BytesWritten         uint64                 `protobuf:"varint,4,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorType            PostStatus_ErrorType   `protobuf:"varint,6,opt,name=error_type,json=errorType,proto3,enum=spacemesh.v1.PostStatus_ErrorType" json:"error_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PostStatus) Reset()         { *m = PostStatus{} }
func (m *PostStatus) String() string { return proto.CompactTextString(m) }
func (*PostStatus) ProtoMessage()    {}
func (*PostStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{18}
}

func (m *PostStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostStatus.Unmarshal(m, b)
}
func (m *PostStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostStatus.Marshal(b, m, deterministic)
}
func (m *PostStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostStatus.Merge(m, src)
}
func (m *PostStatus) XXX_Size() int {
	return xxx_messageInfo_PostStatus.Size(m)
}
func (m *PostStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PostStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PostStatus proto.InternalMessageInfo

func (m *PostStatus) GetPostData() *PostData {
	if m != nil {
		return m.PostData
	}
	return nil
}

func (m *PostStatus) GetFilesStatus() PostStatus_FilesStatus {
	if m != nil {
		return m.FilesStatus
	}
	return PostStatus_FILES_STATUS_UNSPECIFIED
}

func (m *PostStatus) GetInitInProgress() bool {
	if m != nil {
		return m.InitInProgress
	}
	return false
}

func (m *PostStatus) GetBytesWritten() uint64 {
	if m != nil {
		return m.BytesWritten
	}
	return 0
}

func (m *PostStatus) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *PostStatus) GetErrorType() PostStatus_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return PostStatus_ERROR_TYPE_UNSPECIFIED
}

type PostStatusResponse struct {
	Status               *PostStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PostStatusResponse) Reset()         { *m = PostStatusResponse{} }
func (m *PostStatusResponse) String() string { return proto.CompactTextString(m) }
func (*PostStatusResponse) ProtoMessage()    {}
func (*PostStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{19}
}

func (m *PostStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostStatusResponse.Unmarshal(m, b)
}
func (m *PostStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostStatusResponse.Marshal(b, m, deterministic)
}
func (m *PostStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostStatusResponse.Merge(m, src)
}
func (m *PostStatusResponse) XXX_Size() int {
	return xxx_messageInfo_PostStatusResponse.Size(m)
}
func (m *PostStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostStatusResponse proto.InternalMessageInfo

func (m *PostStatusResponse) GetStatus() *PostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type PostDataCreationProgressStreamResponse struct {
	Status               *PostStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PostDataCreationProgressStreamResponse) Reset() {
	*m = PostDataCreationProgressStreamResponse{}
}
func (m *PostDataCreationProgressStreamResponse) String() string { return proto.CompactTextString(m) }
func (*PostDataCreationProgressStreamResponse) ProtoMessage()    {}
func (*PostDataCreationProgressStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bd5dea6a78c4dc4, []int{20}
}

func (m *PostDataCreationProgressStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDataCreationProgressStreamResponse.Unmarshal(m, b)
}
func (m *PostDataCreationProgressStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDataCreationProgressStreamResponse.Marshal(b, m, deterministic)
}
func (m *PostDataCreationProgressStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDataCreationProgressStreamResponse.Merge(m, src)
}
func (m *PostDataCreationProgressStreamResponse) XXX_Size() int {
	return xxx_messageInfo_PostDataCreationProgressStreamResponse.Size(m)
}
func (m *PostDataCreationProgressStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDataCreationProgressStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostDataCreationProgressStreamResponse proto.InternalMessageInfo

func (m *PostDataCreationProgressStreamResponse) GetStatus() *PostStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("spacemesh.v1.ComputeEngineFlag", ComputeEngineFlag_name, ComputeEngineFlag_value)
	proto.RegisterEnum("spacemesh.v1.PostStatus_FilesStatus", PostStatus_FilesStatus_name, PostStatus_FilesStatus_value)
	proto.RegisterEnum("spacemesh.v1.PostStatus_ErrorType", PostStatus_ErrorType_name, PostStatus_ErrorType_value)
	proto.RegisterType((*IsSmeshingResponse)(nil), "spacemesh.v1.IsSmeshingResponse")
	proto.RegisterType((*StartSmeshingResponse)(nil), "spacemesh.v1.StartSmeshingResponse")
	proto.RegisterType((*StopSmeshingResponse)(nil), "spacemesh.v1.StopSmeshingResponse")
	proto.RegisterType((*SetCoinbaseRequest)(nil), "spacemesh.v1.SetCoinbaseRequest")
	proto.RegisterType((*SetCoinbaseResponse)(nil), "spacemesh.v1.SetCoinbaseResponse")
	proto.RegisterType((*MinGasResponse)(nil), "spacemesh.v1.MinGasResponse")
	proto.RegisterType((*SetMinGasRequest)(nil), "spacemesh.v1.SetMinGasRequest")
	proto.RegisterType((*SetMinGasResponse)(nil), "spacemesh.v1.SetMinGasResponse")
	proto.RegisterType((*CreatePostDataResponse)(nil), "spacemesh.v1.CreatePostDataResponse")
	proto.RegisterType((*StopPostDataCreationSessionResponse)(nil), "spacemesh.v1.StopPostDataCreationSessionResponse")
	proto.RegisterType((*SmesherIdResponse)(nil), "spacemesh.v1.SmesherIdResponse")
	proto.RegisterType((*CoinbaseResponse)(nil), "spacemesh.v1.CoinbaseResponse")
	proto.RegisterType((*ComputeEngineFlags)(nil), "spacemesh.v1.ComputeEngineFlags")
	proto.RegisterType((*AvailableComputeEnginesResponse)(nil), "spacemesh.v1.AvailableComputeEnginesResponse")
	proto.RegisterType((*PostData)(nil), "spacemesh.v1.PostData")
	proto.RegisterType((*CreatePostDataRequest)(nil), "spacemesh.v1.CreatePostDataRequest")
	proto.RegisterType((*StopSmeshingRequest)(nil), "spacemesh.v1.StopSmeshingRequest")
	proto.RegisterType((*StopPostDataCreationSessionRequest)(nil), "spacemesh.v1.StopPostDataCreationSessionRequest")
	proto.RegisterType((*PostStatus)(nil), "spacemesh.v1.PostStatus")
	proto.RegisterType((*PostStatusResponse)(nil), "spacemesh.v1.PostStatusResponse")
	proto.RegisterType((*PostDataCreationProgressStreamResponse)(nil), "spacemesh.v1.PostDataCreationProgressStreamResponse")
}

func init() { proto.RegisterFile("spacemesh/v1/smesher_types.proto", fileDescriptor_8bd5dea6a78c4dc4) }

var fileDescriptor_8bd5dea6a78c4dc4 = []byte{
	// 919 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdd, 0x6e, 0xe2, 0x46,
	0x14, 0xc7, 0x0b, 0x61, 0x11, 0x1c, 0xd8, 0xc8, 0x99, 0xcd, 0x07, 0x61, 0xdb, 0x2e, 0x75, 0xaa,
	0x36, 0xca, 0x05, 0xde, 0xcd, 0x56, 0x55, 0x6f, 0xaa, 0xd6, 0x0b, 0x06, 0xb9, 0x4b, 0x08, 0x1d,
	0x43, 0x57, 0xbb, 0x37, 0xd6, 0x00, 0x27, 0xce, 0x48, 0x60, 0xbb, 0x9e, 0x21, 0x55, 0x56, 0xed,
	0x53, 0xf4, 0x7d, 0x7a, 0xd3, 0x17, 0xab, 0xfc, 0x01, 0xc1, 0x40, 0xda, 0x94, 0xdc, 0x79, 0xce,
	0xf9, 0x9f, 0xdf, 0x9c, 0x8f, 0x99, 0x01, 0xa8, 0x09, 0x9f, 0x8d, 0x70, 0x8a, 0xe2, 0x5a, 0xbb,
	0x79, 0xa5, 0x89, 0xf0, 0x03, 0x03, 0x5b, 0xde, 0xfa, 0x28, 0xea, 0x7e, 0xe0, 0x49, 0x8f, 0x94,
	0x17, 0x8a, 0xfa, 0xcd, 0xab, 0x6a, 0x25, 0xa5, 0x5f, 0xd2, 0x55, 0x8f, 0x1c, 0xcf, 0x73, 0x26,
	0xa8, 0x05, 0xfe, 0x48, 0x13, 0x92, 0xc9, 0x59, 0xe2, 0x50, 0x7f, 0x04, 0x62, 0x0a, 0x2b, 0x0c,
	0xe1, 0xae, 0x43, 0x51, 0xf8, 0x9e, 0x2b, 0x90, 0x9c, 0x41, 0x3e, 0x56, 0x55, 0x32, 0xb5, 0xcc,
	0x69, 0xe9, 0x9c, 0xd4, 0xe3, 0xf8, 0x7a, 0xe0, 0x8f, 0xea, 0x56, 0xe4, 0xa1, 0x89, 0x42, 0x6d,
	0xc0, 0x81, 0x25, 0x59, 0x20, 0x1f, 0x05, 0x79, 0x03, 0xfb, 0x96, 0xf4, 0xfc, 0x47, 0x31, 0xbe,
	0x07, 0x62, 0xa1, 0x6c, 0x78, 0xdc, 0x1d, 0x32, 0x81, 0x14, 0x7f, 0x9d, 0xa1, 0x90, 0xe4, 0x6b,
	0xc8, 0xf2, 0x71, 0x12, 0x7d, 0x54, 0x5f, 0x6e, 0x57, 0x5d, 0x1f, 0x8d, 0xbc, 0x99, 0x2b, 0xcd,
	0x31, 0xcd, 0xf2, 0xb1, 0xaa, 0xc3, 0xb3, 0x54, 0xf8, 0x16, 0x19, 0xe8, 0xb0, 0x7b, 0xc1, 0xdd,
	0x36, 0x13, 0x8b, 0x68, 0x0d, 0xf2, 0x53, 0xee, 0x3a, 0x4c, 0x6c, 0xce, 0xc0, 0xe2, 0x53, 0x7f,
	0x82, 0xa6, 0x2b, 0x69, 0x22, 0x53, 0x1b, 0xa0, 0x58, 0x28, 0xe7, 0x94, 0xb8, 0x84, 0xff, 0x0d,
	0xf9, 0x01, 0xf6, 0x96, 0x20, 0x5b, 0x14, 0xd2, 0x84, 0xc3, 0x46, 0x80, 0x4c, 0x62, 0xcf, 0x13,
	0xb2, 0xc9, 0x24, 0xdb, 0x8a, 0xf2, 0x33, 0x9c, 0x84, 0x43, 0x9d, 0x33, 0x22, 0x22, 0xf7, 0x5c,
	0x0b, 0x85, 0xe0, 0x9e, 0xbb, 0x15, 0xf2, 0x2d, 0xec, 0x59, 0xf1, 0x35, 0x30, 0xc7, 0x0b, 0xc0,
	0xb7, 0x00, 0x2c, 0x1e, 0xa5, 0xfd, 0xdf, 0xa3, 0x2e, 0xb2, 0xf9, 0xa7, 0xfa, 0x13, 0x28, 0x6b,
	0xe3, 0xde, 0x96, 0xd5, 0x02, 0xd2, 0xf0, 0xa6, 0xfe, 0x4c, 0xa2, 0xe1, 0x3a, 0xdc, 0xc5, 0xd6,
	0x84, 0x39, 0x82, 0xbc, 0x84, 0xfd, 0x51, 0x6c, 0xb5, 0x31, 0x32, 0xdb, 0x57, 0xa1, 0x3d, 0xe2,
	0x3e, 0xa5, 0x64, 0xb4, 0x16, 0xa1, 0xbe, 0x87, 0x17, 0xfa, 0x0d, 0xe3, 0x13, 0x36, 0x9c, 0x60,
	0x0a, 0x28, 0x96, 0x52, 0x7c, 0x72, 0x47, 0x29, 0x9d, 0xd7, 0xd2, 0xd9, 0xad, 0x67, 0x41, 0x63,
	0xb9, 0xfa, 0x77, 0x06, 0x0a, 0xf3, 0x59, 0x10, 0x02, 0x39, 0x9f, 0xc9, 0xeb, 0x88, 0x51, 0xa4,
	0xd1, 0x37, 0x79, 0x0e, 0xc5, 0x31, 0x93, 0xcc, 0x16, 0xfc, 0x23, 0x56, 0xb2, 0xb5, 0xcc, 0x69,
	0x8e, 0x16, 0x42, 0x83, 0xc5, 0x3f, 0x22, 0x39, 0x84, 0x3c, 0xf3, 0x7d, 0x74, 0xc7, 0x95, 0x9d,
	0x5a, 0xe6, 0xb4, 0x40, 0x93, 0x15, 0xa9, 0x42, 0x41, 0x5e, 0x07, 0x9e, 0x94, 0x13, 0xac, 0xe4,
	0x22, 0xcf, 0x62, 0x4d, 0xe8, 0x3d, 0xe5, 0x3f, 0x79, 0x60, 0xe2, 0x9b, 0x1a, 0xd4, 0x80, 0x83,
	0xd5, 0xa3, 0x19, 0xdf, 0x92, 0x33, 0xc8, 0x85, 0xc9, 0x26, 0x5d, 0x39, 0x4c, 0xc3, 0x17, 0xe2,
	0x48, 0xa3, 0x7e, 0x07, 0xcf, 0xd2, 0xcf, 0x4d, 0x8c, 0xf8, 0x02, 0xca, 0x63, 0x9c, 0xa0, 0x44,
	0xfb, 0x8a, 0x4f, 0x30, 0x6e, 0x70, 0x81, 0x96, 0x62, 0x5b, 0x2b, 0x34, 0xa9, 0x6d, 0x50, 0xff,
	0xf5, 0x4c, 0x3f, 0x18, 0xf4, 0x57, 0x0e, 0x20, 0xa4, 0xc4, 0x07, 0x9c, 0xbc, 0x86, 0xa2, 0xef,
	0x09, 0x69, 0x3f, 0xa0, 0x84, 0x82, 0x3f, 0x1f, 0x62, 0x1b, 0xca, 0x11, 0xdf, 0x4e, 0xee, 0x4f,
	0x38, 0xb3, 0xdd, 0xf3, 0x2f, 0xd7, 0xe3, 0xe2, 0x4d, 0xea, 0xd1, 0xce, 0xc9, 0x8d, 0x2a, 0x5d,
	0xdd, 0x2d, 0xc8, 0x29, 0x28, 0xdc, 0xe5, 0xd2, 0xe6, 0xae, 0xed, 0x07, 0x9e, 0x13, 0xa0, 0x10,
	0xc9, 0x98, 0x77, 0x43, 0xbb, 0xe9, 0xf6, 0x12, 0x2b, 0x39, 0x81, 0xa7, 0xc3, 0x5b, 0x89, 0xc2,
	0xfe, 0x2d, 0xe0, 0x52, 0xa2, 0x1b, 0xcd, 0x3c, 0x47, 0xcb, 0x91, 0xf1, 0x5d, 0x6c, 0x0b, 0x45,
	0x18, 0x04, 0x5e, 0x60, 0x4f, 0x51, 0x08, 0xe6, 0x60, 0x34, 0xf0, 0x22, 0x2d, 0x47, 0xc6, 0x8b,
	0xd8, 0x46, 0x74, 0x80, 0x58, 0x14, 0xfe, 0x4e, 0x55, 0xf2, 0x51, 0xea, 0xea, 0xbd, 0xa9, 0x1b,
	0xa1, 0xb4, 0x7f, 0xeb, 0x23, 0x2d, 0xe2, 0xfc, 0x53, 0xfd, 0x1d, 0x4a, 0x4b, 0x25, 0x91, 0x4f,
	0xa1, 0xd2, 0x32, 0x3b, 0x86, 0x65, 0x5b, 0x7d, 0xbd, 0x3f, 0xb0, 0xec, 0x41, 0xd7, 0xea, 0x19,
	0x0d, 0xb3, 0x65, 0x1a, 0x4d, 0xe5, 0x13, 0x52, 0x85, 0xc3, 0x94, 0xb7, 0x7b, 0xd9, 0xb7, 0x5b,
	0x97, 0x83, 0x6e, 0x53, 0xc9, 0x90, 0x0a, 0xec, 0xa7, 0x7c, 0x3d, 0x9d, 0xf6, 0x4d, 0xbd, 0xa3,
	0x64, 0xc9, 0x31, 0x1c, 0xa4, 0x3c, 0x8d, 0xcb, 0x8b, 0x5e, 0xc7, 0xe8, 0x1b, 0xca, 0x8e, 0xfa,
	0x07, 0x14, 0x17, 0x59, 0x85, 0x74, 0x83, 0xd2, 0x4b, 0x6a, 0xf7, 0xdf, 0xf7, 0x8c, 0x95, 0x9d,
	0x3f, 0x83, 0xe3, 0x25, 0x5f, 0x88, 0x4b, 0x6d, 0x7e, 0x0c, 0x07, 0x4b, 0x6e, 0x6a, 0xe8, 0x4d,
	0x3b, 0x5a, 0x2b, 0xd9, 0x15, 0xea, 0x3b, 0x6a, 0xf6, 0x8d, 0xc4, 0xb7, 0x13, 0xbe, 0x38, 0x77,
	0xfd, 0x59, 0x3c, 0x0e, 0x2f, 0x57, 0x1e, 0xd3, 0xca, 0x7d, 0x1d, 0x5d, 0x3c, 0xa9, 0x1f, 0xe0,
	0xab, 0xd5, 0xd3, 0x3c, 0x9f, 0xb6, 0x25, 0x03, 0x64, 0xd3, 0xed, 0xd9, 0x67, 0x7f, 0x66, 0x60,
	0x6f, 0xed, 0x5e, 0x93, 0x13, 0x78, 0x11, 0xb6, 0x71, 0x10, 0x16, 0xd3, 0x6d, 0x9b, 0x5d, 0xc3,
	0x6e, 0x75, 0xf4, 0xf6, 0x4a, 0xd3, 0x9e, 0xc3, 0xd1, 0x26, 0x51, 0xa3, 0x37, 0x50, 0x32, 0xe1,
	0xa4, 0x37, 0x3a, 0x07, 0x4d, 0x5d, 0xc9, 0x92, 0xcf, 0xa1, 0xba, 0xc9, 0xfb, 0xcb, 0xa0, 0xf3,
	0x56, 0xef, 0x2a, 0xb9, 0x37, 0xdf, 0x7c, 0x38, 0x77, 0xb8, 0xbc, 0x9e, 0x0d, 0xeb, 0x23, 0x6f,
	0xaa, 0x2d, 0x6a, 0xf0, 0x84, 0xc6, 0x7c, 0xae, 0x05, 0x38, 0x41, 0x26, 0x50, 0x73, 0x3c, 0x6d,
	0xf9, 0xef, 0xd4, 0x30, 0x1f, 0xfd, 0x61, 0x7a, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c,
	0xd9, 0xe3, 0x62, 0x95, 0x09, 0x00, 0x00,
}
