// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: spacemesh/v1/smesher_types.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Compute API class
type ComputeApiClass int32

const (
	ComputeApiClass_COMPUTE_API_CLASS_UNSPECIFIED ComputeApiClass = 0
	ComputeApiClass_COMPUTE_API_CLASS_CPU         ComputeApiClass = 1 // useful for testing on systems without a cuda or vulkan GPU
	ComputeApiClass_COMPUTE_API_CLASS_CUDA        ComputeApiClass = 2
	ComputeApiClass_COMPUTE_API_CLASS_VULKAN      ComputeApiClass = 3
)

// Enum value maps for ComputeApiClass.
var (
	ComputeApiClass_name = map[int32]string{
		0: "COMPUTE_API_CLASS_UNSPECIFIED",
		1: "COMPUTE_API_CLASS_CPU",
		2: "COMPUTE_API_CLASS_CUDA",
		3: "COMPUTE_API_CLASS_VULKAN",
	}
	ComputeApiClass_value = map[string]int32{
		"COMPUTE_API_CLASS_UNSPECIFIED": 0,
		"COMPUTE_API_CLASS_CPU":         1,
		"COMPUTE_API_CLASS_CUDA":        2,
		"COMPUTE_API_CLASS_VULKAN":      3,
	}
)

func (x ComputeApiClass) Enum() *ComputeApiClass {
	p := new(ComputeApiClass)
	*p = x
	return p
}

func (x ComputeApiClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeApiClass) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_smesher_types_proto_enumTypes[0].Descriptor()
}

func (ComputeApiClass) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_smesher_types_proto_enumTypes[0]
}

func (x ComputeApiClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComputeApiClass.Descriptor instead.
func (ComputeApiClass) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{0}
}

type PostStatus_FilesStatus int32

const (
	PostStatus_FILES_STATUS_UNSPECIFIED PostStatus_FilesStatus = 0 // Lane's favorite impossible value
	PostStatus_FILES_STATUS_NOT_FOUND   PostStatus_FilesStatus = 1 // Expected data files do not exist
	PostStatus_FILES_STATUS_PARTIAL     PostStatus_FilesStatus = 2 // Some files exist and init can be continued (and may be in progress)
	PostStatus_FILES_STATUS_COMPLETE    PostStatus_FilesStatus = 3 // Expected data files are available and verified
)

// Enum value maps for PostStatus_FilesStatus.
var (
	PostStatus_FilesStatus_name = map[int32]string{
		0: "FILES_STATUS_UNSPECIFIED",
		1: "FILES_STATUS_NOT_FOUND",
		2: "FILES_STATUS_PARTIAL",
		3: "FILES_STATUS_COMPLETE",
	}
	PostStatus_FilesStatus_value = map[string]int32{
		"FILES_STATUS_UNSPECIFIED": 0,
		"FILES_STATUS_NOT_FOUND":   1,
		"FILES_STATUS_PARTIAL":     2,
		"FILES_STATUS_COMPLETE":    3,
	}
)

func (x PostStatus_FilesStatus) Enum() *PostStatus_FilesStatus {
	p := new(PostStatus_FilesStatus)
	*p = x
	return p
}

func (x PostStatus_FilesStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus_FilesStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_smesher_types_proto_enumTypes[1].Descriptor()
}

func (PostStatus_FilesStatus) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_smesher_types_proto_enumTypes[1]
}

func (x PostStatus_FilesStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus_FilesStatus.Descriptor instead.
func (PostStatus_FilesStatus) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{16, 0}
}

type PostStatus_ErrorType int32

const (
	PostStatus_ERROR_TYPE_UNSPECIFIED    PostStatus_ErrorType = 0 // Lane's favorite imposible value
	PostStatus_ERROR_TYPE_FILE_NOT_FOUND PostStatus_ErrorType = 1 // All expected post data files not found in expected path
	PostStatus_ERROR_TYPE_READ_ERROR     PostStatus_ErrorType = 2 // Failure to read from a data file
	PostStatus_ERROR_TYPE_WRITE_ERROR    PostStatus_ErrorType = 3 // Failure to write to a data file
)

// Enum value maps for PostStatus_ErrorType.
var (
	PostStatus_ErrorType_name = map[int32]string{
		0: "ERROR_TYPE_UNSPECIFIED",
		1: "ERROR_TYPE_FILE_NOT_FOUND",
		2: "ERROR_TYPE_READ_ERROR",
		3: "ERROR_TYPE_WRITE_ERROR",
	}
	PostStatus_ErrorType_value = map[string]int32{
		"ERROR_TYPE_UNSPECIFIED":    0,
		"ERROR_TYPE_FILE_NOT_FOUND": 1,
		"ERROR_TYPE_READ_ERROR":     2,
		"ERROR_TYPE_WRITE_ERROR":    3,
	}
)

func (x PostStatus_ErrorType) Enum() *PostStatus_ErrorType {
	p := new(PostStatus_ErrorType)
	*p = x
	return p
}

func (x PostStatus_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_smesher_types_proto_enumTypes[2].Descriptor()
}

func (PostStatus_ErrorType) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_smesher_types_proto_enumTypes[2]
}

func (x PostStatus_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus_ErrorType.Descriptor instead.
func (PostStatus_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{16, 1}
}

type IsSmeshingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSmeshing bool `protobuf:"varint,1,opt,name=is_smeshing,json=isSmeshing,proto3" json:"is_smeshing,omitempty"`
}

func (x *IsSmeshingResponse) Reset() {
	*x = IsSmeshingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsSmeshingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSmeshingResponse) ProtoMessage() {}

func (x *IsSmeshingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSmeshingResponse.ProtoReflect.Descriptor instead.
func (*IsSmeshingResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{0}
}

func (x *IsSmeshingResponse) GetIsSmeshing() bool {
	if x != nil {
		return x.IsSmeshing
	}
	return false
}

type StartSmeshingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coinbase *AccountId    `protobuf:"bytes,1,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Opts     *PostInitOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *StartSmeshingRequest) Reset() {
	*x = StartSmeshingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSmeshingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSmeshingRequest) ProtoMessage() {}

func (x *StartSmeshingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSmeshingRequest.ProtoReflect.Descriptor instead.
func (*StartSmeshingRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{1}
}

func (x *StartSmeshingRequest) GetCoinbase() *AccountId {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *StartSmeshingRequest) GetOpts() *PostInitOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type StartSmeshingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StartSmeshingResponse) Reset() {
	*x = StartSmeshingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSmeshingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSmeshingResponse) ProtoMessage() {}

func (x *StartSmeshingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSmeshingResponse.ProtoReflect.Descriptor instead.
func (*StartSmeshingResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{2}
}

func (x *StartSmeshingResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopSmeshingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StopSmeshingResponse) Reset() {
	*x = StopSmeshingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSmeshingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSmeshingResponse) ProtoMessage() {}

func (x *StopSmeshingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSmeshingResponse.ProtoReflect.Descriptor instead.
func (*StopSmeshingResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{3}
}

func (x *StopSmeshingResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type SetCoinbaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *AccountId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SetCoinbaseRequest) Reset() {
	*x = SetCoinbaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoinbaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoinbaseRequest) ProtoMessage() {}

func (x *SetCoinbaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoinbaseRequest.ProtoReflect.Descriptor instead.
func (*SetCoinbaseRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{4}
}

func (x *SetCoinbaseRequest) GetId() *AccountId {
	if x != nil {
		return x.Id
	}
	return nil
}

type SetCoinbaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetCoinbaseResponse) Reset() {
	*x = SetCoinbaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoinbaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoinbaseResponse) ProtoMessage() {}

func (x *SetCoinbaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoinbaseResponse.ProtoReflect.Descriptor instead.
func (*SetCoinbaseResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{5}
}

func (x *SetCoinbaseResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type MinGasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mingas *SimpleInt `protobuf:"bytes,1,opt,name=mingas,proto3" json:"mingas,omitempty"`
}

func (x *MinGasResponse) Reset() {
	*x = MinGasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinGasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinGasResponse) ProtoMessage() {}

func (x *MinGasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinGasResponse.ProtoReflect.Descriptor instead.
func (*MinGasResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{6}
}

func (x *MinGasResponse) GetMingas() *SimpleInt {
	if x != nil {
		return x.Mingas
	}
	return nil
}

type SetMinGasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mingas *SimpleInt `protobuf:"bytes,1,opt,name=mingas,proto3" json:"mingas,omitempty"`
}

func (x *SetMinGasRequest) Reset() {
	*x = SetMinGasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMinGasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMinGasRequest) ProtoMessage() {}

func (x *SetMinGasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMinGasRequest.ProtoReflect.Descriptor instead.
func (*SetMinGasRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{7}
}

func (x *SetMinGasRequest) GetMingas() *SimpleInt {
	if x != nil {
		return x.Mingas
	}
	return nil
}

type SetMinGasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetMinGasResponse) Reset() {
	*x = SetMinGasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMinGasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMinGasResponse) ProtoMessage() {}

func (x *SetMinGasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMinGasResponse.ProtoReflect.Descriptor instead.
func (*SetMinGasResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{8}
}

func (x *SetMinGasResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type SmesherIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *SmesherIDResponse) Reset() {
	*x = SmesherIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmesherIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmesherIDResponse) ProtoMessage() {}

func (x *SmesherIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmesherIDResponse.ProtoReflect.Descriptor instead.
func (*SmesherIDResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{9}
}

func (x *SmesherIDResponse) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

type CoinbaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CoinbaseResponse) Reset() {
	*x = CoinbaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinbaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinbaseResponse) ProtoMessage() {}

func (x *CoinbaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinbaseResponse.ProtoReflect.Descriptor instead.
func (*CoinbaseResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{10}
}

func (x *CoinbaseResponse) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

type PostComputeProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                     // 0, 1, 2...
	Model       string          `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                                                                // e.g. Nvidia GTX 2700
	ComputeApi  ComputeApiClass `protobuf:"varint,3,opt,name=compute_api,json=computeApi,proto3,enum=spacemesh.v1.ComputeApiClass" json:"compute_api,omitempty"` // A provided compute api
	Performance uint64          `protobuf:"varint,4,opt,name=performance,proto3" json:"performance,omitempty"`                                                   // Estimated performance in hashes per second
}

func (x *PostComputeProvider) Reset() {
	*x = PostComputeProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostComputeProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostComputeProvider) ProtoMessage() {}

func (x *PostComputeProvider) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostComputeProvider.ProtoReflect.Descriptor instead.
func (*PostComputeProvider) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{11}
}

func (x *PostComputeProvider) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostComputeProvider) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PostComputeProvider) GetComputeApi() ComputeApiClass {
	if x != nil {
		return x.ComputeApi
	}
	return ComputeApiClass_COMPUTE_API_CLASS_UNSPECIFIED
}

func (x *PostComputeProvider) GetPerformance() uint64 {
	if x != nil {
		return x.Performance
	}
	return 0
}

type PostComputeProvidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostComputeProvider []*PostComputeProvider `protobuf:"bytes,1,rep,name=post_compute_provider,json=postComputeProvider,proto3" json:"post_compute_provider,omitempty"`
}

func (x *PostComputeProvidersResponse) Reset() {
	*x = PostComputeProvidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostComputeProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostComputeProvidersResponse) ProtoMessage() {}

func (x *PostComputeProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostComputeProvidersResponse.ProtoReflect.Descriptor instead.
func (*PostComputeProvidersResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{12}
}

func (x *PostComputeProvidersResponse) GetPostComputeProvider() []*PostComputeProvider {
	if x != nil {
		return x.PostComputeProvider
	}
	return nil
}

// Post init options. Used to define the requested options and by
// other messages which contain the options.
type PostInitOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataDir           string `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`                                  // User provided path to create the post data files at
	NumUnits          uint32 `protobuf:"varint,2,opt,name=num_units,json=numUnits,proto3" json:"num_units,omitempty"`                              // Number of PoST data commitment units to generate
	NumFiles          uint32 `protobuf:"varint,3,opt,name=num_files,json=numFiles,proto3" json:"num_files,omitempty"`                              // Number of files to equally distribute the labels among
	ComputeProviderId uint32 `protobuf:"varint,4,opt,name=compute_provider_id,json=computeProviderId,proto3" json:"compute_provider_id,omitempty"` // A PostProvider id
	Throttle          bool   `protobuf:"varint,5,opt,name=throttle,proto3" json:"throttle,omitempty"`                                              // Throttle down setup phase computations while user is interactive on system
}

func (x *PostInitOpts) Reset() {
	*x = PostInitOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostInitOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInitOpts) ProtoMessage() {}

func (x *PostInitOpts) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInitOpts.ProtoReflect.Descriptor instead.
func (*PostInitOpts) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{13}
}

func (x *PostInitOpts) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *PostInitOpts) GetNumUnits() uint32 {
	if x != nil {
		return x.NumUnits
	}
	return 0
}

func (x *PostInitOpts) GetNumFiles() uint32 {
	if x != nil {
		return x.NumFiles
	}
	return 0
}

func (x *PostInitOpts) GetComputeProviderId() uint32 {
	if x != nil {
		return x.ComputeProviderId
	}
	return 0
}

func (x *PostInitOpts) GetThrottle() bool {
	if x != nil {
		return x.Throttle
	}
	return false
}

type CreatePostDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opts *PostInitOpts `protobuf:"bytes,1,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *CreatePostDataRequest) Reset() {
	*x = CreatePostDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostDataRequest) ProtoMessage() {}

func (x *CreatePostDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostDataRequest.ProtoReflect.Descriptor instead.
func (*CreatePostDataRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePostDataRequest) GetOpts() *PostInitOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

// Param passed to methods to indicate a request to delete data files
type StopSmeshingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteFiles bool `protobuf:"varint,1,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"`
}

func (x *StopSmeshingRequest) Reset() {
	*x = StopSmeshingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSmeshingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSmeshingRequest) ProtoMessage() {}

func (x *StopSmeshingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSmeshingRequest.ProtoReflect.Descriptor instead.
func (*StopSmeshingRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{15}
}

func (x *StopSmeshingRequest) GetDeleteFiles() bool {
	if x != nil {
		return x.DeleteFiles
	}
	return false
}

// Proof of space data status
type PostStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastOpts       *PostInitOpts          `protobuf:"bytes,1,opt,name=last_opts,json=lastOpts,proto3" json:"last_opts,omitempty"` // options set previously by the user
	FilesStatus    PostStatus_FilesStatus `protobuf:"varint,2,opt,name=files_status,json=filesStatus,proto3,enum=spacemesh.v1.PostStatus_FilesStatus" json:"files_status,omitempty"`
	InitInProgress bool                   `protobuf:"varint,3,opt,name=init_in_progress,json=initInProgress,proto3" json:"init_in_progress,omitempty"` // True if init process is currently in progress
	LabelsWritten  uint64                 `protobuf:"varint,4,opt,name=labels_written,json=labelsWritten,proto3" json:"labels_written,omitempty"`      // Bytes written to the data files (actual total files sizes)
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`          // Last init process error message
	ErrorType      PostStatus_ErrorType   `protobuf:"varint,6,opt,name=error_type,json=errorType,proto3,enum=spacemesh.v1.PostStatus_ErrorType" json:"error_type,omitempty"`
}

func (x *PostStatus) Reset() {
	*x = PostStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatus) ProtoMessage() {}

func (x *PostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatus.ProtoReflect.Descriptor instead.
func (*PostStatus) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{16}
}

func (x *PostStatus) GetLastOpts() *PostInitOpts {
	if x != nil {
		return x.LastOpts
	}
	return nil
}

func (x *PostStatus) GetFilesStatus() PostStatus_FilesStatus {
	if x != nil {
		return x.FilesStatus
	}
	return PostStatus_FILES_STATUS_UNSPECIFIED
}

func (x *PostStatus) GetInitInProgress() bool {
	if x != nil {
		return x.InitInProgress
	}
	return false
}

func (x *PostStatus) GetLabelsWritten() uint64 {
	if x != nil {
		return x.LabelsWritten
	}
	return 0
}

func (x *PostStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PostStatus) GetErrorType() PostStatus_ErrorType {
	if x != nil {
		return x.ErrorType
	}
	return PostStatus_ERROR_TYPE_UNSPECIFIED
}

type PostStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *PostStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PostStatusResponse) Reset() {
	*x = PostStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatusResponse) ProtoMessage() {}

func (x *PostStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatusResponse.ProtoReflect.Descriptor instead.
func (*PostStatusResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{17}
}

func (x *PostStatusResponse) GetStatus() *PostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type PostDataCreationProgressStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *PostStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PostDataCreationProgressStreamResponse) Reset() {
	*x = PostDataCreationProgressStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostDataCreationProgressStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDataCreationProgressStreamResponse) ProtoMessage() {}

func (x *PostDataCreationProgressStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDataCreationProgressStreamResponse.ProtoReflect.Descriptor instead.
func (*PostDataCreationProgressStreamResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{18}
}

func (x *PostDataCreationProgressStreamResponse) GetStatus() *PostStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type EstimatedRewardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EstimatedRewardsRequest) Reset() {
	*x = EstimatedRewardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimatedRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatedRewardsRequest) ProtoMessage() {}

func (x *EstimatedRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatedRewardsRequest.ProtoReflect.Descriptor instead.
func (*EstimatedRewardsRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{19}
}

// Estimated rewards for the next epoch. Note that this is a global value that will be the
// same for all smeshers, and is based on the default minimum commitment size and fixed
// epoch length, both of which are network params.
type EstimatedRewardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The amount of the total estimated reward in the next upcoming epoch
	Amount *Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The number of PoST data commitment units that this estimated reward corresponds to (part of global config)
	NumUnits uint32 `protobuf:"varint,2,opt,name=num_units,json=numUnits,proto3" json:"num_units,omitempty"`
}

func (x *EstimatedRewardsResponse) Reset() {
	*x = EstimatedRewardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimatedRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatedRewardsResponse) ProtoMessage() {}

func (x *EstimatedRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatedRewardsResponse.ProtoReflect.Descriptor instead.
func (*EstimatedRewardsResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{20}
}

func (x *EstimatedRewardsResponse) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *EstimatedRewardsResponse) GetNumUnits() uint32 {
	if x != nil {
		return x.NumUnits
	}
	return 0
}

// TODO: document
type ConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BitsPerLabel  uint32 `protobuf:"varint,1,opt,name=bits_per_label,json=bitsPerLabel,proto3" json:"bits_per_label,omitempty"`
	LabelsPerUnit uint64 `protobuf:"varint,2,opt,name=labels_per_unit,json=labelsPerUnit,proto3" json:"labels_per_unit,omitempty"`
	MinNumUnits   uint32 `protobuf:"varint,3,opt,name=min_num_units,json=minNumUnits,proto3" json:"min_num_units,omitempty"`
	MaxNumUnits   uint32 `protobuf:"varint,4,opt,name=max_num_units,json=maxNumUnits,proto3" json:"max_num_units,omitempty"`
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_smesher_types_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_smesher_types_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigResponse) GetBitsPerLabel() uint32 {
	if x != nil {
		return x.BitsPerLabel
	}
	return 0
}

func (x *ConfigResponse) GetLabelsPerUnit() uint64 {
	if x != nil {
		return x.LabelsPerUnit
	}
	return 0
}

func (x *ConfigResponse) GetMinNumUnits() uint32 {
	if x != nil {
		return x.MinNumUnits
	}
	return 0
}

func (x *ConfigResponse) GetMaxNumUnits() uint32 {
	if x != nil {
		return x.MaxNumUnits
	}
	return 0
}

var File_spacemesh_v1_smesher_types_proto protoreflect.FileDescriptor

var file_spacemesh_v1_smesher_types_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x6d, 0x65, 0x73, 0x68, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31,
	0x1a, 0x18, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x12, 0x49, 0x73, 0x53, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f,
	0x73, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x53, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x7b, 0x0a, 0x14, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x08, 0x63,
	0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74,
	0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x43, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x14,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x6d, 0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x3d, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x41, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x4d, 0x69, 0x6e, 0x47, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x67, 0x61, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x52, 0x06, 0x6d,
	0x69, 0x6e, 0x67, 0x61, 0x73, 0x22, 0x43, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x47,
	0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x69, 0x6e,
	0x67, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x49,
	0x6e, 0x74, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x67, 0x61, 0x73, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x4d, 0x69, 0x6e, 0x47, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x11, 0x53,
	0x6d, 0x65, 0x73, 0x68, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x10, 0x43, 0x6f, 0x69, 0x6e,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x3e, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x41, 0x70,
	0x69, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x41,
	0x70, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x6e, 0x63, 0x65, 0x22, 0x75, 0x0a, 0x1c, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x15, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x13, 0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x0c,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x55,
	0x6e, 0x69, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x47, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x73,
	0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x6d,
	0x65, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x22, 0xc4, 0x04, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x37, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x69,
	0x74, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x57, 0x72, 0x69, 0x74, 0x74,
	0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7c, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x49, 0x4c,
	0x45, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x46, 0x49, 0x4c, 0x45, 0x53,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x45, 0x53, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x19, 0x0a,
	0x15, 0x46, 0x49, 0x4c, 0x45, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f,
	0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x22, 0x7d, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01,
	0x12, 0x19, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x46, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x5a, 0x0a, 0x26, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x45,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x18, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x22, 0xa6, 0x01,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x62, 0x69, 0x74, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x69, 0x74, 0x73, 0x50, 0x65,
	0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x55, 0x6e, 0x69,
	0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x4e, 0x75,
	0x6d, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x2a, 0x89, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x41, 0x70, 0x69, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4f,
	0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a,
	0x15, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x5f, 0x43, 0x4c, 0x41,
	0x53, 0x53, 0x5f, 0x43, 0x50, 0x55, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x4d, 0x50,
	0x55, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x43, 0x55,
	0x44, 0x41, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f,
	0x41, 0x50, 0x49, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x56, 0x55, 0x4c, 0x4b, 0x41, 0x4e,
	0x10, 0x03, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacemesh_v1_smesher_types_proto_rawDescOnce sync.Once
	file_spacemesh_v1_smesher_types_proto_rawDescData = file_spacemesh_v1_smesher_types_proto_rawDesc
)

func file_spacemesh_v1_smesher_types_proto_rawDescGZIP() []byte {
	file_spacemesh_v1_smesher_types_proto_rawDescOnce.Do(func() {
		file_spacemesh_v1_smesher_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacemesh_v1_smesher_types_proto_rawDescData)
	})
	return file_spacemesh_v1_smesher_types_proto_rawDescData
}

var file_spacemesh_v1_smesher_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacemesh_v1_smesher_types_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_spacemesh_v1_smesher_types_proto_goTypes = []interface{}{
	(ComputeApiClass)(0),                           // 0: spacemesh.v1.ComputeApiClass
	(PostStatus_FilesStatus)(0),                    // 1: spacemesh.v1.PostStatus.FilesStatus
	(PostStatus_ErrorType)(0),                      // 2: spacemesh.v1.PostStatus.ErrorType
	(*IsSmeshingResponse)(nil),                     // 3: spacemesh.v1.IsSmeshingResponse
	(*StartSmeshingRequest)(nil),                   // 4: spacemesh.v1.StartSmeshingRequest
	(*StartSmeshingResponse)(nil),                  // 5: spacemesh.v1.StartSmeshingResponse
	(*StopSmeshingResponse)(nil),                   // 6: spacemesh.v1.StopSmeshingResponse
	(*SetCoinbaseRequest)(nil),                     // 7: spacemesh.v1.SetCoinbaseRequest
	(*SetCoinbaseResponse)(nil),                    // 8: spacemesh.v1.SetCoinbaseResponse
	(*MinGasResponse)(nil),                         // 9: spacemesh.v1.MinGasResponse
	(*SetMinGasRequest)(nil),                       // 10: spacemesh.v1.SetMinGasRequest
	(*SetMinGasResponse)(nil),                      // 11: spacemesh.v1.SetMinGasResponse
	(*SmesherIDResponse)(nil),                      // 12: spacemesh.v1.SmesherIDResponse
	(*CoinbaseResponse)(nil),                       // 13: spacemesh.v1.CoinbaseResponse
	(*PostComputeProvider)(nil),                    // 14: spacemesh.v1.PostComputeProvider
	(*PostComputeProvidersResponse)(nil),           // 15: spacemesh.v1.PostComputeProvidersResponse
	(*PostInitOpts)(nil),                           // 16: spacemesh.v1.PostInitOpts
	(*CreatePostDataRequest)(nil),                  // 17: spacemesh.v1.CreatePostDataRequest
	(*StopSmeshingRequest)(nil),                    // 18: spacemesh.v1.StopSmeshingRequest
	(*PostStatus)(nil),                             // 19: spacemesh.v1.PostStatus
	(*PostStatusResponse)(nil),                     // 20: spacemesh.v1.PostStatusResponse
	(*PostDataCreationProgressStreamResponse)(nil), // 21: spacemesh.v1.PostDataCreationProgressStreamResponse
	(*EstimatedRewardsRequest)(nil),                // 22: spacemesh.v1.EstimatedRewardsRequest
	(*EstimatedRewardsResponse)(nil),               // 23: spacemesh.v1.EstimatedRewardsResponse
	(*ConfigResponse)(nil),                         // 24: spacemesh.v1.ConfigResponse
	(*AccountId)(nil),                              // 25: spacemesh.v1.AccountId
	(*status.Status)(nil),                          // 26: google.rpc.Status
	(*SimpleInt)(nil),                              // 27: spacemesh.v1.SimpleInt
	(*Amount)(nil),                                 // 28: spacemesh.v1.Amount
}
var file_spacemesh_v1_smesher_types_proto_depIdxs = []int32{
	25, // 0: spacemesh.v1.StartSmeshingRequest.coinbase:type_name -> spacemesh.v1.AccountId
	16, // 1: spacemesh.v1.StartSmeshingRequest.opts:type_name -> spacemesh.v1.PostInitOpts
	26, // 2: spacemesh.v1.StartSmeshingResponse.status:type_name -> google.rpc.Status
	26, // 3: spacemesh.v1.StopSmeshingResponse.status:type_name -> google.rpc.Status
	25, // 4: spacemesh.v1.SetCoinbaseRequest.id:type_name -> spacemesh.v1.AccountId
	26, // 5: spacemesh.v1.SetCoinbaseResponse.status:type_name -> google.rpc.Status
	27, // 6: spacemesh.v1.MinGasResponse.mingas:type_name -> spacemesh.v1.SimpleInt
	27, // 7: spacemesh.v1.SetMinGasRequest.mingas:type_name -> spacemesh.v1.SimpleInt
	26, // 8: spacemesh.v1.SetMinGasResponse.status:type_name -> google.rpc.Status
	25, // 9: spacemesh.v1.SmesherIDResponse.account_id:type_name -> spacemesh.v1.AccountId
	25, // 10: spacemesh.v1.CoinbaseResponse.account_id:type_name -> spacemesh.v1.AccountId
	0,  // 11: spacemesh.v1.PostComputeProvider.compute_api:type_name -> spacemesh.v1.ComputeApiClass
	14, // 12: spacemesh.v1.PostComputeProvidersResponse.post_compute_provider:type_name -> spacemesh.v1.PostComputeProvider
	16, // 13: spacemesh.v1.CreatePostDataRequest.opts:type_name -> spacemesh.v1.PostInitOpts
	16, // 14: spacemesh.v1.PostStatus.last_opts:type_name -> spacemesh.v1.PostInitOpts
	1,  // 15: spacemesh.v1.PostStatus.files_status:type_name -> spacemesh.v1.PostStatus.FilesStatus
	2,  // 16: spacemesh.v1.PostStatus.error_type:type_name -> spacemesh.v1.PostStatus.ErrorType
	19, // 17: spacemesh.v1.PostStatusResponse.status:type_name -> spacemesh.v1.PostStatus
	19, // 18: spacemesh.v1.PostDataCreationProgressStreamResponse.status:type_name -> spacemesh.v1.PostStatus
	28, // 19: spacemesh.v1.EstimatedRewardsResponse.amount:type_name -> spacemesh.v1.Amount
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_spacemesh_v1_smesher_types_proto_init() }
func file_spacemesh_v1_smesher_types_proto_init() {
	if File_spacemesh_v1_smesher_types_proto != nil {
		return
	}
	file_spacemesh_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_spacemesh_v1_smesher_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsSmeshingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSmeshingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSmeshingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSmeshingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoinbaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoinbaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinGasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMinGasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMinGasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmesherIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinbaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostComputeProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostComputeProvidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostInitOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSmeshingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostDataCreationProgressStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimatedRewardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimatedRewardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_smesher_types_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacemesh_v1_smesher_types_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacemesh_v1_smesher_types_proto_goTypes,
		DependencyIndexes: file_spacemesh_v1_smesher_types_proto_depIdxs,
		EnumInfos:         file_spacemesh_v1_smesher_types_proto_enumTypes,
		MessageInfos:      file_spacemesh_v1_smesher_types_proto_msgTypes,
	}.Build()
	File_spacemesh_v1_smesher_types_proto = out.File
	file_spacemesh_v1_smesher_types_proto_rawDesc = nil
	file_spacemesh_v1_smesher_types_proto_goTypes = nil
	file_spacemesh_v1_smesher_types_proto_depIdxs = nil
}
