// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: spacemesh/v1/types.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SmartContractTransaction_TransactionType int32

const (
	SmartContractTransaction_TRANSACTION_TYPE_UNSPECIFIED     SmartContractTransaction_TransactionType = 0
	SmartContractTransaction_TRANSACTION_TYPE_APP             SmartContractTransaction_TransactionType = 1 // smart contract method
	SmartContractTransaction_TRANSACTION_TYPE_APP_SPAWN_APP   SmartContractTransaction_TransactionType = 2 // deploy app from template using svm terminology
	SmartContractTransaction_TRANSACTION_TYPE_DEPLOY_TEMPLATE SmartContractTransaction_TransactionType = 3 // deploy app template code to mesh
)

// Enum value maps for SmartContractTransaction_TransactionType.
var (
	SmartContractTransaction_TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_APP",
		2: "TRANSACTION_TYPE_APP_SPAWN_APP",
		3: "TRANSACTION_TYPE_DEPLOY_TEMPLATE",
	}
	SmartContractTransaction_TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED":     0,
		"TRANSACTION_TYPE_APP":             1,
		"TRANSACTION_TYPE_APP_SPAWN_APP":   2,
		"TRANSACTION_TYPE_DEPLOY_TEMPLATE": 3,
	}
)

func (x SmartContractTransaction_TransactionType) Enum() *SmartContractTransaction_TransactionType {
	p := new(SmartContractTransaction_TransactionType)
	*p = x
	return p
}

func (x SmartContractTransaction_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmartContractTransaction_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_types_proto_enumTypes[0].Descriptor()
}

func (SmartContractTransaction_TransactionType) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_types_proto_enumTypes[0]
}

func (x SmartContractTransaction_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmartContractTransaction_TransactionType.Descriptor instead.
func (SmartContractTransaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{10, 0}
}

type Signature_Scheme int32

const (
	Signature_SCHEME_UNSPECIFIED       Signature_Scheme = 0
	Signature_SCHEME_ED25519           Signature_Scheme = 1 // standard Ed25519 scheme
	Signature_SCHEME_ED25519_PLUS_PLUS Signature_Scheme = 2 // sm-modified ED25519 , a.k.a. ED25519++
)

// Enum value maps for Signature_Scheme.
var (
	Signature_Scheme_name = map[int32]string{
		0: "SCHEME_UNSPECIFIED",
		1: "SCHEME_ED25519",
		2: "SCHEME_ED25519_PLUS_PLUS",
	}
	Signature_Scheme_value = map[string]int32{
		"SCHEME_UNSPECIFIED":       0,
		"SCHEME_ED25519":           1,
		"SCHEME_ED25519_PLUS_PLUS": 2,
	}
)

func (x Signature_Scheme) Enum() *Signature_Scheme {
	p := new(Signature_Scheme)
	*p = x
	return p
}

func (x Signature_Scheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signature_Scheme) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_types_proto_enumTypes[1].Descriptor()
}

func (Signature_Scheme) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_types_proto_enumTypes[1]
}

func (x Signature_Scheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signature_Scheme.Descriptor instead.
func (Signature_Scheme) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{11, 0}
}

type Layer_LayerStatus int32

const (
	Layer_LAYER_STATUS_UNSPECIFIED Layer_LayerStatus = 0 // not yet approved or confirmed
	Layer_LAYER_STATUS_APPROVED    Layer_LayerStatus = 1 // approved by hare
	Layer_LAYER_STATUS_CONFIRMED   Layer_LayerStatus = 2 // confirmed by tortoise
)

// Enum value maps for Layer_LayerStatus.
var (
	Layer_LayerStatus_name = map[int32]string{
		0: "LAYER_STATUS_UNSPECIFIED",
		1: "LAYER_STATUS_APPROVED",
		2: "LAYER_STATUS_CONFIRMED",
	}
	Layer_LayerStatus_value = map[string]int32{
		"LAYER_STATUS_UNSPECIFIED": 0,
		"LAYER_STATUS_APPROVED":    1,
		"LAYER_STATUS_CONFIRMED":   2,
	}
)

func (x Layer_LayerStatus) Enum() *Layer_LayerStatus {
	p := new(Layer_LayerStatus)
	*p = x
	return p
}

func (x Layer_LayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer_LayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v1_types_proto_enumTypes[2].Descriptor()
}

func (Layer_LayerStatus) Type() protoreflect.EnumType {
	return &file_spacemesh_v1_types_proto_enumTypes[2]
}

func (x Layer_LayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer_LayerStatus.Descriptor instead.
func (Layer_LayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{16, 0}
}

type SimpleInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SimpleInt) Reset() {
	*x = SimpleInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleInt) ProtoMessage() {}

func (x *SimpleInt) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleInt.ProtoReflect.Descriptor instead.
func (*SimpleInt) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleInt) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SimpleString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SimpleString) Reset() {
	*x = SimpleString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleString) ProtoMessage() {}

func (x *SimpleString) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleString.ProtoReflect.Descriptor instead.
func (*SimpleString) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A non-negative coin amount, in smidge
type Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Amount) Reset() {
	*x = Amount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Amount) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *AccountId) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId *AccountId `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // account public address
	Counter   uint64     `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`                     // aka nonce
	Balance   *Amount    `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`                      // known account balance
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Account) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Account) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Account) GetBalance() *Amount {
	if x != nil {
		return x.Balance
	}
	return nil
}

type TransactionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TransactionId) Reset() {
	*x = TransactionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionId) ProtoMessage() {}

func (x *TransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionId.ProtoReflect.Descriptor instead.
func (*TransactionId) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ActivationId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ActivationId) Reset() {
	*x = ActivationId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationId) ProtoMessage() {}

func (x *ActivationId) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationId.ProtoReflect.Descriptor instead.
func (*ActivationId) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ActivationId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type SmesherId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SmesherId) Reset() {
	*x = SmesherId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmesherId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmesherId) ProtoMessage() {}

func (x *SmesherId) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmesherId.ProtoReflect.Descriptor instead.
func (*SmesherId) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *SmesherId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GasOffered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GasProvided uint64 `protobuf:"varint,1,opt,name=gas_provided,json=gasProvided,proto3" json:"gas_provided,omitempty"`
	GasPrice    uint64 `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
}

func (x *GasOffered) Reset() {
	*x = GasOffered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GasOffered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasOffered) ProtoMessage() {}

func (x *GasOffered) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasOffered.ProtoReflect.Descriptor instead.
func (*GasOffered) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *GasOffered) GetGasProvided() uint64 {
	if x != nil {
		return x.GasProvided
	}
	return 0
}

func (x *GasOffered) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

// Data specific to a simple coin transaction.
type CoinTransferTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver *AccountId `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *CoinTransferTransaction) Reset() {
	*x = CoinTransferTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinTransferTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinTransferTransaction) ProtoMessage() {}

func (x *CoinTransferTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinTransferTransaction.ProtoReflect.Descriptor instead.
func (*CoinTransferTransaction) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *CoinTransferTransaction) GetReceiver() *AccountId {
	if x != nil {
		return x.Receiver
	}
	return nil
}

// Data specific to a smart contract transaction.
type SmartContractTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      SmartContractTransaction_TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=spacemesh.v1.SmartContractTransaction_TransactionType" json:"type,omitempty"`
	Data      []byte                                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // packed binary arguments, including ABI selector
	AccountId *AccountId                               `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // address of smart contract or template
}

func (x *SmartContractTransaction) Reset() {
	*x = SmartContractTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartContractTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartContractTransaction) ProtoMessage() {}

func (x *SmartContractTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartContractTransaction.ProtoReflect.Descriptor instead.
func (*SmartContractTransaction) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *SmartContractTransaction) GetType() SmartContractTransaction_TransactionType {
	if x != nil {
		return x.Type
	}
	return SmartContractTransaction_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *SmartContractTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SmartContractTransaction) GetAccountId() *AccountId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

// A simple signature data
type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme    Signature_Scheme `protobuf:"varint,1,opt,name=scheme,proto3,enum=spacemesh.v1.Signature_Scheme" json:"scheme,omitempty"` // the signature's scheme
	Signature []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                               // the signature itself
	PublicKey []byte           `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`              // included in schemes which require signer to provide a public key
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *Signature) GetScheme() Signature_Scheme {
	if x != nil {
		return x.Scheme
	}
	return Signature_SCHEME_UNSPECIFIED
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// An Activation "transaction" (ATX)
type Activation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             *ActivationId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Layer          uint64        `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"`                                         // the layer that this activation is part of
	SmesherId      *SmesherId    `protobuf:"bytes,3,opt,name=smesher_id,json=smesherId,proto3" json:"smesher_id,omitempty"`                 // id of smesher who created the ATX
	Coinbase       *AccountId    `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty"`                                    // coinbase account id
	PrevAtx        *ActivationId `protobuf:"bytes,5,opt,name=prev_atx,json=prevAtx,proto3" json:"prev_atx,omitempty"`                       // previous ATX pointed to
	CommitmentSize uint64        `protobuf:"varint,6,opt,name=commitment_size,json=commitmentSize,proto3" json:"commitment_size,omitempty"` // commitment size in bytes
}

func (x *Activation) Reset() {
	*x = Activation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activation) ProtoMessage() {}

func (x *Activation) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activation.ProtoReflect.Descriptor instead.
func (*Activation) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *Activation) GetId() *ActivationId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Activation) GetLayer() uint64 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *Activation) GetSmesherId() *SmesherId {
	if x != nil {
		return x.SmesherId
	}
	return nil
}

func (x *Activation) GetCoinbase() *AccountId {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *Activation) GetPrevAtx() *ActivationId {
	if x != nil {
		return x.PrevAtx
	}
	return nil
}

func (x *Activation) GetCommitmentSize() uint64 {
	if x != nil {
		return x.CommitmentSize
	}
	return 0
}

// An immutable Spacemesh transaction.
// do not include mutable data such as tx state or result.
type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *TransactionId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Datum:
	//	*Transaction_CoinTransfer
	//	*Transaction_SmartContract
	Datum      isTransaction_Datum `protobuf_oneof:"datum"`
	Sender     *AccountId          `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`                           // tx originator, should match signer inside Signature
	GasOffered *GasOffered         `protobuf:"bytes,5,opt,name=gas_offered,json=gasOffered,proto3" json:"gas_offered,omitempty"` // gas price and max gas offered
	Amount     *Amount             `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`                           // amount of coin transfered in this tx by sender
	Counter    uint64              `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`                        // tx counter aka nonce
	Signature  *Signature          `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                     // sender signature on transaction
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *Transaction) GetId() *TransactionId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (m *Transaction) GetDatum() isTransaction_Datum {
	if m != nil {
		return m.Datum
	}
	return nil
}

func (x *Transaction) GetCoinTransfer() *CoinTransferTransaction {
	if x, ok := x.GetDatum().(*Transaction_CoinTransfer); ok {
		return x.CoinTransfer
	}
	return nil
}

func (x *Transaction) GetSmartContract() *SmartContractTransaction {
	if x, ok := x.GetDatum().(*Transaction_SmartContract); ok {
		return x.SmartContract
	}
	return nil
}

func (x *Transaction) GetSender() *AccountId {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transaction) GetGasOffered() *GasOffered {
	if x != nil {
		return x.GasOffered
	}
	return nil
}

func (x *Transaction) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isTransaction_Datum interface {
	isTransaction_Datum()
}

type Transaction_CoinTransfer struct {
	CoinTransfer *CoinTransferTransaction `protobuf:"bytes,2,opt,name=coin_transfer,json=coinTransfer,proto3,oneof"`
}

type Transaction_SmartContract struct {
	SmartContract *SmartContractTransaction `protobuf:"bytes,3,opt,name=smart_contract,json=smartContract,proto3,oneof"`
}

func (*Transaction_CoinTransfer) isTransaction_Datum() {}

func (*Transaction_SmartContract) isTransaction_Datum() {}

type Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer         uint64     `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`                                      // layer award was paid in
	Total         *Amount    `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`                                       // total reward paid (sum of tx fee and layer reward)
	LayerReward   *Amount    `protobuf:"bytes,3,opt,name=layer_reward,json=layerReward,proto3" json:"layer_reward,omitempty"`        // tx_fee = total - layer_reward
	LayerComputed uint64     `protobuf:"varint,4,opt,name=layer_computed,json=layerComputed,proto3" json:"layer_computed,omitempty"` // layer number of the layer when reward was computed
	Coinbase      *AccountId `protobuf:"bytes,5,opt,name=coinbase,proto3" json:"coinbase,omitempty"`                                 // account awarded this reward
	Smesher       *SmesherId `protobuf:"bytes,6,opt,name=smesher,proto3" json:"smesher,omitempty"`                                   // id of smesher who earned this reward
}

func (x *Reward) Reset() {
	*x = Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *Reward) GetLayer() uint64 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *Reward) GetTotal() *Amount {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Reward) GetLayerReward() *Amount {
	if x != nil {
		return x.LayerReward
	}
	return nil
}

func (x *Reward) GetLayerComputed() uint64 {
	if x != nil {
		return x.LayerComputed
	}
	return 0
}

func (x *Reward) GetCoinbase() *AccountId {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *Reward) GetSmesher() *SmesherId {
	if x != nil {
		return x.Smesher
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // block hash
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *Block) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Layer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number        uint64            `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // layer number - not hash - layer content may change
	Status        Layer_LayerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=spacemesh.v1.Layer_LayerStatus" json:"status,omitempty"`
	Hash          []byte            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`                                          // computer layer hash - do we need this?
	Blocks        []*Block          `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`                                      // layer's blocks
	Activations   []*Activation     `protobuf:"bytes,5,rep,name=activations,proto3" json:"activations,omitempty"`                            // list of layer's activations
	RootStateHash []byte            `protobuf:"bytes,6,opt,name=root_state_hash,json=rootStateHash,proto3" json:"root_state_hash,omitempty"` // when available - the root state hash of global state in this layer
}

func (x *Layer) Reset() {
	*x = Layer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *Layer) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Layer) GetStatus() Layer_LayerStatus {
	if x != nil {
		return x.Status
	}
	return Layer_LAYER_STATUS_UNSPECIFIED
}

func (x *Layer) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Layer) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Layer) GetActivations() []*Activation {
	if x != nil {
		return x.Activations
	}
	return nil
}

func (x *Layer) GetRootStateHash() []byte {
	if x != nil {
		return x.RootStateHash
	}
	return nil
}

type AppEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId *TransactionId `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // the transaction that called the code
	Message       string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // the event's string emitted from code
}

func (x *AppEvent) Reset() {
	*x = AppEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacemesh_v1_types_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEvent) ProtoMessage() {}

func (x *AppEvent) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v1_types_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEvent.ProtoReflect.Descriptor instead.
func (*AppEvent) Descriptor() ([]byte, []int) {
	return file_spacemesh_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *AppEvent) GetTransactionId() *TransactionId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *AppEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spacemesh_v1_types_proto protoreflect.FileDescriptor

var file_spacemesh_v1_types_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x21, 0x0a, 0x09, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x1e, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x25, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x53, 0x6d, 0x65, 0x73, 0x68,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x0a, 0x47, 0x61, 0x73, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x67, 0x61, 0x73, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x4e, 0x0a, 0x17, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x22, 0xcc, 0x02, 0x0a, 0x18, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x4a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6d, 0x61,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x36, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x5f,
	0x53, 0x50, 0x41, 0x57, 0x4e, 0x5f, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x10,
	0x03, 0x22, 0xd4, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x36, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x22, 0x52, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x45,
	0x5f, 0x45, 0x44, 0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x43,
	0x48, 0x45, 0x4d, 0x45, 0x5f, 0x45, 0x44, 0x32, 0x35, 0x35, 0x31, 0x39, 0x5f, 0x50, 0x4c, 0x55,
	0x53, 0x5f, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x02, 0x22, 0x9b, 0x02, 0x0a, 0x0a, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x6d, 0x65,
	0x73, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6d, 0x65,
	0x73, 0x68, 0x65, 0x72, 0x49, 0x64, 0x52, 0x09, 0x73, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x08, 0x63, 0x6f,
	0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x61,
	0x74, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x41, 0x74, 0x78, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xcd, 0x03, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x4c, 0x0a, 0x0d, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x12, 0x4f, 0x0a, 0x0e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0b, 0x67, 0x61, 0x73, 0x5f, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x73, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x65, 0x64, 0x52, 0x0a, 0x67, 0x61, 0x73, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x12, 0x2c,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x64, 0x61, 0x74, 0x75, 0x6d, 0x22, 0x92, 0x02, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x0c, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x0b, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x08,
	0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x73, 0x6d, 0x65, 0x73,
	0x68, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x07, 0x73, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x72, 0x22, 0x56, 0x0a, 0x05, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0xe1, 0x02, 0x0a, 0x05, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x2b, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12,
	0x3a, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x72, 0x6f, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x62, 0x0a, 0x0b, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x19, 0x0a, 0x15, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x02, 0x22, 0x68, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x73, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacemesh_v1_types_proto_rawDescOnce sync.Once
	file_spacemesh_v1_types_proto_rawDescData = file_spacemesh_v1_types_proto_rawDesc
)

func file_spacemesh_v1_types_proto_rawDescGZIP() []byte {
	file_spacemesh_v1_types_proto_rawDescOnce.Do(func() {
		file_spacemesh_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacemesh_v1_types_proto_rawDescData)
	})
	return file_spacemesh_v1_types_proto_rawDescData
}

var file_spacemesh_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacemesh_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_spacemesh_v1_types_proto_goTypes = []interface{}{
	(SmartContractTransaction_TransactionType)(0), // 0: spacemesh.v1.SmartContractTransaction.TransactionType
	(Signature_Scheme)(0),                         // 1: spacemesh.v1.Signature.Scheme
	(Layer_LayerStatus)(0),                        // 2: spacemesh.v1.Layer.LayerStatus
	(*SimpleInt)(nil),                             // 3: spacemesh.v1.SimpleInt
	(*SimpleString)(nil),                          // 4: spacemesh.v1.SimpleString
	(*Amount)(nil),                                // 5: spacemesh.v1.Amount
	(*AccountId)(nil),                             // 6: spacemesh.v1.AccountId
	(*Account)(nil),                               // 7: spacemesh.v1.Account
	(*TransactionId)(nil),                         // 8: spacemesh.v1.TransactionId
	(*ActivationId)(nil),                          // 9: spacemesh.v1.ActivationId
	(*SmesherId)(nil),                             // 10: spacemesh.v1.SmesherId
	(*GasOffered)(nil),                            // 11: spacemesh.v1.GasOffered
	(*CoinTransferTransaction)(nil),               // 12: spacemesh.v1.CoinTransferTransaction
	(*SmartContractTransaction)(nil),              // 13: spacemesh.v1.SmartContractTransaction
	(*Signature)(nil),                             // 14: spacemesh.v1.Signature
	(*Activation)(nil),                            // 15: spacemesh.v1.Activation
	(*Transaction)(nil),                           // 16: spacemesh.v1.Transaction
	(*Reward)(nil),                                // 17: spacemesh.v1.Reward
	(*Block)(nil),                                 // 18: spacemesh.v1.Block
	(*Layer)(nil),                                 // 19: spacemesh.v1.Layer
	(*AppEvent)(nil),                              // 20: spacemesh.v1.AppEvent
}
var file_spacemesh_v1_types_proto_depIdxs = []int32{
	6,  // 0: spacemesh.v1.Account.account_id:type_name -> spacemesh.v1.AccountId
	5,  // 1: spacemesh.v1.Account.balance:type_name -> spacemesh.v1.Amount
	6,  // 2: spacemesh.v1.CoinTransferTransaction.receiver:type_name -> spacemesh.v1.AccountId
	0,  // 3: spacemesh.v1.SmartContractTransaction.type:type_name -> spacemesh.v1.SmartContractTransaction.TransactionType
	6,  // 4: spacemesh.v1.SmartContractTransaction.account_id:type_name -> spacemesh.v1.AccountId
	1,  // 5: spacemesh.v1.Signature.scheme:type_name -> spacemesh.v1.Signature.Scheme
	9,  // 6: spacemesh.v1.Activation.id:type_name -> spacemesh.v1.ActivationId
	10, // 7: spacemesh.v1.Activation.smesher_id:type_name -> spacemesh.v1.SmesherId
	6,  // 8: spacemesh.v1.Activation.coinbase:type_name -> spacemesh.v1.AccountId
	9,  // 9: spacemesh.v1.Activation.prev_atx:type_name -> spacemesh.v1.ActivationId
	8,  // 10: spacemesh.v1.Transaction.id:type_name -> spacemesh.v1.TransactionId
	12, // 11: spacemesh.v1.Transaction.coin_transfer:type_name -> spacemesh.v1.CoinTransferTransaction
	13, // 12: spacemesh.v1.Transaction.smart_contract:type_name -> spacemesh.v1.SmartContractTransaction
	6,  // 13: spacemesh.v1.Transaction.sender:type_name -> spacemesh.v1.AccountId
	11, // 14: spacemesh.v1.Transaction.gas_offered:type_name -> spacemesh.v1.GasOffered
	5,  // 15: spacemesh.v1.Transaction.amount:type_name -> spacemesh.v1.Amount
	14, // 16: spacemesh.v1.Transaction.signature:type_name -> spacemesh.v1.Signature
	5,  // 17: spacemesh.v1.Reward.total:type_name -> spacemesh.v1.Amount
	5,  // 18: spacemesh.v1.Reward.layer_reward:type_name -> spacemesh.v1.Amount
	6,  // 19: spacemesh.v1.Reward.coinbase:type_name -> spacemesh.v1.AccountId
	10, // 20: spacemesh.v1.Reward.smesher:type_name -> spacemesh.v1.SmesherId
	16, // 21: spacemesh.v1.Block.transactions:type_name -> spacemesh.v1.Transaction
	2,  // 22: spacemesh.v1.Layer.status:type_name -> spacemesh.v1.Layer.LayerStatus
	18, // 23: spacemesh.v1.Layer.blocks:type_name -> spacemesh.v1.Block
	15, // 24: spacemesh.v1.Layer.activations:type_name -> spacemesh.v1.Activation
	8,  // 25: spacemesh.v1.AppEvent.transaction_id:type_name -> spacemesh.v1.TransactionId
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_spacemesh_v1_types_proto_init() }
func file_spacemesh_v1_types_proto_init() {
	if File_spacemesh_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spacemesh_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivationId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmesherId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GasOffered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinTransferTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartContractTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacemesh_v1_types_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spacemesh_v1_types_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*Transaction_CoinTransfer)(nil),
		(*Transaction_SmartContract)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacemesh_v1_types_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacemesh_v1_types_proto_goTypes,
		DependencyIndexes: file_spacemesh_v1_types_proto_depIdxs,
		EnumInfos:         file_spacemesh_v1_types_proto_enumTypes,
		MessageInfos:      file_spacemesh_v1_types_proto_msgTypes,
	}.Build()
	File_spacemesh_v1_types_proto = out.File
	file_spacemesh_v1_types_proto_rawDesc = nil
	file_spacemesh_v1_types_proto_goTypes = nil
	file_spacemesh_v1_types_proto_depIdxs = nil
}
