// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: spacemesh/v2beta1/tx.proto

package spacemeshv2beta1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionState is the "journey" of a tx from mempool to block inclusion to
// mesh to STF processing. To know whether or not the tx actually succeeded,
// and its side effects, check tx_state.
type TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNSPECIFIED        TransactionState = 0 // default state
	TransactionState_TRANSACTION_STATE_REJECTED           TransactionState = 1 // rejected from mempool due to, e.g., invalid syntax
	TransactionState_TRANSACTION_STATE_INSUFFICIENT_FUNDS TransactionState = 2 // rejected from mempool by funds check
	TransactionState_TRANSACTION_STATE_CONFLICTING        TransactionState = 3 // rejected from mempool due to conflicting counter
	TransactionState_TRANSACTION_STATE_MEMPOOL            TransactionState = 4 // in mempool but not on the mesh yet
	TransactionState_TRANSACTION_STATE_MESH               TransactionState = 5 // submitted to the mesh
	TransactionState_TRANSACTION_STATE_PROCESSED          TransactionState = 6 // processed by STF; check Receipt for success or failure
	TransactionState_TRANSACTION_STATE_INEFFECTUAL        TransactionState = 7 // removed from mempool and will be forgotten and never executed
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNSPECIFIED",
		1: "TRANSACTION_STATE_REJECTED",
		2: "TRANSACTION_STATE_INSUFFICIENT_FUNDS",
		3: "TRANSACTION_STATE_CONFLICTING",
		4: "TRANSACTION_STATE_MEMPOOL",
		5: "TRANSACTION_STATE_MESH",
		6: "TRANSACTION_STATE_PROCESSED",
		7: "TRANSACTION_STATE_INEFFECTUAL",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNSPECIFIED":        0,
		"TRANSACTION_STATE_REJECTED":           1,
		"TRANSACTION_STATE_INSUFFICIENT_FUNDS": 2,
		"TRANSACTION_STATE_CONFLICTING":        3,
		"TRANSACTION_STATE_MEMPOOL":            4,
		"TRANSACTION_STATE_MESH":               5,
		"TRANSACTION_STATE_PROCESSED":          6,
		"TRANSACTION_STATE_INEFFECTUAL":        7,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v2beta1_tx_proto_enumTypes[0].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_spacemesh_v2beta1_tx_proto_enumTypes[0]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{0}
}

type Transaction_TransactionType int32

const (
	Transaction_TRANSACTION_TYPE_UNSPECIFIED      Transaction_TransactionType = 0
	Transaction_TRANSACTION_TYPE_SINGLE_SIG_SEND  Transaction_TransactionType = 1
	Transaction_TRANSACTION_TYPE_SINGLE_SIG_SPAWN Transaction_TransactionType = 2
	// Deprecated: Marked as deprecated in spacemesh/v2beta1/tx.proto.
	Transaction_TRANSACTION_TYPE_SINGLE_SIG_SELFSPAWN Transaction_TransactionType = 3
	Transaction_TRANSACTION_TYPE_MULTI_SIG_SEND       Transaction_TransactionType = 4
	Transaction_TRANSACTION_TYPE_MULTI_SIG_SPAWN      Transaction_TransactionType = 5
	// Deprecated: Marked as deprecated in spacemesh/v2beta1/tx.proto.
	Transaction_TRANSACTION_TYPE_MULTI_SIG_SELFSPAWN Transaction_TransactionType = 6
	Transaction_TRANSACTION_TYPE_VESTING_SPAWN       Transaction_TransactionType = 7
	Transaction_TRANSACTION_TYPE_VAULT_SPAWN         Transaction_TransactionType = 8
	Transaction_TRANSACTION_TYPE_DRAIN_VAULT         Transaction_TransactionType = 9
)

// Enum value maps for Transaction_TransactionType.
var (
	Transaction_TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_SINGLE_SIG_SEND",
		2: "TRANSACTION_TYPE_SINGLE_SIG_SPAWN",
		3: "TRANSACTION_TYPE_SINGLE_SIG_SELFSPAWN",
		4: "TRANSACTION_TYPE_MULTI_SIG_SEND",
		5: "TRANSACTION_TYPE_MULTI_SIG_SPAWN",
		6: "TRANSACTION_TYPE_MULTI_SIG_SELFSPAWN",
		7: "TRANSACTION_TYPE_VESTING_SPAWN",
		8: "TRANSACTION_TYPE_VAULT_SPAWN",
		9: "TRANSACTION_TYPE_DRAIN_VAULT",
	}
	Transaction_TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED":          0,
		"TRANSACTION_TYPE_SINGLE_SIG_SEND":      1,
		"TRANSACTION_TYPE_SINGLE_SIG_SPAWN":     2,
		"TRANSACTION_TYPE_SINGLE_SIG_SELFSPAWN": 3,
		"TRANSACTION_TYPE_MULTI_SIG_SEND":       4,
		"TRANSACTION_TYPE_MULTI_SIG_SPAWN":      5,
		"TRANSACTION_TYPE_MULTI_SIG_SELFSPAWN":  6,
		"TRANSACTION_TYPE_VESTING_SPAWN":        7,
		"TRANSACTION_TYPE_VAULT_SPAWN":          8,
		"TRANSACTION_TYPE_DRAIN_VAULT":          9,
	}
)

func (x Transaction_TransactionType) Enum() *Transaction_TransactionType {
	p := new(Transaction_TransactionType)
	*p = x
	return p
}

func (x Transaction_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v2beta1_tx_proto_enumTypes[1].Descriptor()
}

func (Transaction_TransactionType) Type() protoreflect.EnumType {
	return &file_spacemesh_v2beta1_tx_proto_enumTypes[1]
}

func (x Transaction_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_TransactionType.Descriptor instead.
func (Transaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{0, 0}
}

type TransactionResult_Status int32

const (
	TransactionResult_TRANSACTION_STATUS_UNSPECIFIED TransactionResult_Status = 0
	TransactionResult_TRANSACTION_STATUS_SUCCESS     TransactionResult_Status = 1
	TransactionResult_TRANSACTION_STATUS_FAILURE     TransactionResult_Status = 2
	TransactionResult_TRANSACTION_STATUS_INVALID     TransactionResult_Status = 3
)

// Enum value maps for TransactionResult_Status.
var (
	TransactionResult_Status_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_SUCCESS",
		2: "TRANSACTION_STATUS_FAILURE",
		3: "TRANSACTION_STATUS_INVALID",
	}
	TransactionResult_Status_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_SUCCESS":     1,
		"TRANSACTION_STATUS_FAILURE":     2,
		"TRANSACTION_STATUS_INVALID":     3,
	}
)

func (x TransactionResult_Status) Enum() *TransactionResult_Status {
	p := new(TransactionResult_Status)
	*p = x
	return p
}

func (x TransactionResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_spacemesh_v2beta1_tx_proto_enumTypes[2].Descriptor()
}

func (TransactionResult_Status) Type() protoreflect.EnumType {
	return &file_spacemesh_v2beta1_tx_proto_enumTypes[2]
}

func (x TransactionResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionResult_Status.Descriptor instead.
func (TransactionResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{8, 0}
}

// An immutable Spacemesh transaction.
// do not include mutable data such as tx state or result.
type Transaction struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            []byte                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Principal     string                      `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"` // principal account address
	Template      string                      `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`   // template account address
	Method        uint32                      `protobuf:"varint,4,opt,name=method,proto3" json:"method,omitempty"`      // this is actually limited by uint8, but no type for that.
	Nonce         *Nonce                      `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MaxGas        uint64                      `protobuf:"varint,6,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`       // max gas units consumed by tx
	GasPrice      uint64                      `protobuf:"varint,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"` // fee per unit gas, in smidge
	MaxSpend      uint64                      `protobuf:"varint,8,opt,name=max_spend,json=maxSpend,proto3" json:"max_spend,omitempty"`
	Raw           []byte                      `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty"`
	Type          Transaction_TransactionType `protobuf:"varint,10,opt,name=type,proto3,enum=spacemesh.v2beta1.Transaction_TransactionType" json:"type,omitempty"`
	Contents      *TransactionContents        `protobuf:"bytes,11,opt,name=contents,proto3" json:"contents,omitempty"` // parsed transaction contents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Transaction) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Transaction) GetMethod() uint32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *Transaction) GetNonce() *Nonce {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Transaction) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *Transaction) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *Transaction) GetMaxSpend() uint64 {
	if x != nil {
		return x.MaxSpend
	}
	return 0
}

func (x *Transaction) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Transaction) GetType() Transaction_TransactionType {
	if x != nil {
		return x.Type
	}
	return Transaction_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetContents() *TransactionContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

type ContentsSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // recipient account
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`          // amount in smidge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentsSend) Reset() {
	*x = ContentsSend{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentsSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsSend) ProtoMessage() {}

func (x *ContentsSend) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsSend.ProtoReflect.Descriptor instead.
func (*ContentsSend) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *ContentsSend) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContentsSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ContentsSingleSigSpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentsSingleSigSpawn) Reset() {
	*x = ContentsSingleSigSpawn{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentsSingleSigSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsSingleSigSpawn) ProtoMessage() {}

func (x *ContentsSingleSigSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsSingleSigSpawn.ProtoReflect.Descriptor instead.
func (*ContentsSingleSigSpawn) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *ContentsSingleSigSpawn) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type ContentsMultiSigSpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      uint32                 `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"` // number of required signatures
	Pubkey        []string               `protobuf:"bytes,2,rep,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentsMultiSigSpawn) Reset() {
	*x = ContentsMultiSigSpawn{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentsMultiSigSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsMultiSigSpawn) ProtoMessage() {}

func (x *ContentsMultiSigSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsMultiSigSpawn.ProtoReflect.Descriptor instead.
func (*ContentsMultiSigSpawn) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *ContentsMultiSigSpawn) GetRequired() uint32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *ContentsMultiSigSpawn) GetPubkey() []string {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type ContentsVaultSpawn struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Owner               string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"` // owner account
	TotalAmount         uint64                 `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	InitialUnlockAmount uint64                 `protobuf:"varint,3,opt,name=initial_unlock_amount,json=initialUnlockAmount,proto3" json:"initial_unlock_amount,omitempty"`
	VestingStart        uint32                 `protobuf:"varint,4,opt,name=vesting_start,json=vestingStart,proto3" json:"vesting_start,omitempty"` // as layer number
	VestingEnd          uint32                 `protobuf:"varint,5,opt,name=vesting_end,json=vestingEnd,proto3" json:"vesting_end,omitempty"`       // as layer number
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContentsVaultSpawn) Reset() {
	*x = ContentsVaultSpawn{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentsVaultSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsVaultSpawn) ProtoMessage() {}

func (x *ContentsVaultSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsVaultSpawn.ProtoReflect.Descriptor instead.
func (*ContentsVaultSpawn) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *ContentsVaultSpawn) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ContentsVaultSpawn) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ContentsVaultSpawn) GetInitialUnlockAmount() uint64 {
	if x != nil {
		return x.InitialUnlockAmount
	}
	return 0
}

func (x *ContentsVaultSpawn) GetVestingStart() uint32 {
	if x != nil {
		return x.VestingStart
	}
	return 0
}

func (x *ContentsVaultSpawn) GetVestingEnd() uint32 {
	if x != nil {
		return x.VestingEnd
	}
	return 0
}

type ContentsDrainVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentsDrainVault) Reset() {
	*x = ContentsDrainVault{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentsDrainVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentsDrainVault) ProtoMessage() {}

func (x *ContentsDrainVault) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentsDrainVault.ProtoReflect.Descriptor instead.
func (*ContentsDrainVault) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *ContentsDrainVault) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *ContentsDrainVault) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContentsDrainVault) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionContents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Contents:
	//
	//	*TransactionContents_Send
	//	*TransactionContents_SingleSigSpawn
	//	*TransactionContents_MultiSigSpawn
	//	*TransactionContents_VestingSpawn
	//	*TransactionContents_VaultSpawn
	//	*TransactionContents_DrainVault
	Contents      isTransactionContents_Contents `protobuf_oneof:"contents"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionContents) Reset() {
	*x = TransactionContents{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionContents) ProtoMessage() {}

func (x *TransactionContents) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionContents.ProtoReflect.Descriptor instead.
func (*TransactionContents) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionContents) GetContents() isTransactionContents_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *TransactionContents) GetSend() *ContentsSend {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *TransactionContents) GetSingleSigSpawn() *ContentsSingleSigSpawn {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_SingleSigSpawn); ok {
			return x.SingleSigSpawn
		}
	}
	return nil
}

func (x *TransactionContents) GetMultiSigSpawn() *ContentsMultiSigSpawn {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_MultiSigSpawn); ok {
			return x.MultiSigSpawn
		}
	}
	return nil
}

func (x *TransactionContents) GetVestingSpawn() *ContentsMultiSigSpawn {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_VestingSpawn); ok {
			return x.VestingSpawn
		}
	}
	return nil
}

func (x *TransactionContents) GetVaultSpawn() *ContentsVaultSpawn {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_VaultSpawn); ok {
			return x.VaultSpawn
		}
	}
	return nil
}

func (x *TransactionContents) GetDrainVault() *ContentsDrainVault {
	if x != nil {
		if x, ok := x.Contents.(*TransactionContents_DrainVault); ok {
			return x.DrainVault
		}
	}
	return nil
}

type isTransactionContents_Contents interface {
	isTransactionContents_Contents()
}

type TransactionContents_Send struct {
	Send *ContentsSend `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type TransactionContents_SingleSigSpawn struct {
	SingleSigSpawn *ContentsSingleSigSpawn `protobuf:"bytes,2,opt,name=single_sig_spawn,json=singleSigSpawn,proto3,oneof"`
}

type TransactionContents_MultiSigSpawn struct {
	MultiSigSpawn *ContentsMultiSigSpawn `protobuf:"bytes,3,opt,name=multi_sig_spawn,json=multiSigSpawn,proto3,oneof"`
}

type TransactionContents_VestingSpawn struct {
	VestingSpawn *ContentsMultiSigSpawn `protobuf:"bytes,4,opt,name=vesting_spawn,json=vestingSpawn,proto3,oneof"`
}

type TransactionContents_VaultSpawn struct {
	VaultSpawn *ContentsVaultSpawn `protobuf:"bytes,5,opt,name=vault_spawn,json=vaultSpawn,proto3,oneof"`
}

type TransactionContents_DrainVault struct {
	DrainVault *ContentsDrainVault `protobuf:"bytes,6,opt,name=drain_vault,json=drainVault,proto3,oneof"`
}

func (*TransactionContents_Send) isTransactionContents_Contents() {}

func (*TransactionContents_SingleSigSpawn) isTransactionContents_Contents() {}

func (*TransactionContents_MultiSigSpawn) isTransactionContents_Contents() {}

func (*TransactionContents_VestingSpawn) isTransactionContents_Contents() {}

func (*TransactionContents_VaultSpawn) isTransactionContents_Contents() {}

func (*TransactionContents_DrainVault) isTransactionContents_Contents() {}

type Nonce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counter       uint64                 `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nonce) Reset() {
	*x = Nonce{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nonce) ProtoMessage() {}

func (x *Nonce) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nonce.ProtoReflect.Descriptor instead.
func (*Nonce) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *Nonce) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type TransactionResult struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Status           TransactionResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=spacemesh.v2beta1.TransactionResult_Status" json:"status,omitempty"` // status of the transaction
	Message          string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GasConsumed      uint64                   `protobuf:"varint,3,opt,name=gas_consumed,json=gasConsumed,proto3" json:"gas_consumed,omitempty"`               // in units of gas
	Fee              uint64                   `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`                                                  // in smidge
	Block            []byte                   `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`                                               // block hash
	Layer            uint32                   `protobuf:"varint,6,opt,name=layer,proto3" json:"layer,omitempty"`                                              // layer number
	TouchedAddresses []string                 `protobuf:"bytes,7,rep,name=touched_addresses,json=touchedAddresses,proto3" json:"touched_addresses,omitempty"` // addresses touched by the tx
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionResult) Reset() {
	*x = TransactionResult{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResult) ProtoMessage() {}

func (x *TransactionResult) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResult.ProtoReflect.Descriptor instead.
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionResult) GetStatus() TransactionResult_Status {
	if x != nil {
		return x.Status
	}
	return TransactionResult_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionResult) GetGasConsumed() uint64 {
	if x != nil {
		return x.GasConsumed
	}
	return 0
}

func (x *TransactionResult) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionResult) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TransactionResult) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *TransactionResult) GetTouchedAddresses() []string {
	if x != nil {
		return x.TouchedAddresses
	}
	return nil
}

type TransactionStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLayer    uint32                 `protobuf:"varint,1,opt,name=start_layer,json=startLayer,proto3" json:"start_layer,omitempty"` // Required: starting layer for transaction streaming.
	EndLayer      *uint32                `protobuf:"varint,2,opt,name=end_layer,json=endLayer,proto3,oneof" json:"end_layer,omitempty"` // Ending layer for transaction streaming.
	Txid          [][]byte               `protobuf:"bytes,3,rep,name=txid,proto3" json:"txid,omitempty"`                                // Filter: specific transaction IDs.
	Principal     *string                `protobuf:"bytes,4,opt,name=principal,proto3,oneof" json:"principal,omitempty"`                // Filter by principal address
	Watch         bool                   `protobuf:"varint,5,opt,name=watch,proto3" json:"watch,omitempty"`                             // Continue watching for new transactions.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStreamRequest) Reset() {
	*x = TransactionStreamRequest{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStreamRequest) ProtoMessage() {}

func (x *TransactionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStreamRequest.ProtoReflect.Descriptor instead.
func (*TransactionStreamRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionStreamRequest) GetStartLayer() uint32 {
	if x != nil {
		return x.StartLayer
	}
	return 0
}

func (x *TransactionStreamRequest) GetEndLayer() uint32 {
	if x != nil && x.EndLayer != nil {
		return *x.EndLayer
	}
	return 0
}

func (x *TransactionStreamRequest) GetTxid() [][]byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *TransactionStreamRequest) GetPrincipal() string {
	if x != nil && x.Principal != nil {
		return *x.Principal
	}
	return ""
}

func (x *TransactionStreamRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLayer    *uint32                `protobuf:"varint,1,opt,name=start_layer,json=startLayer,proto3,oneof" json:"start_layer,omitempty"`                          // Starting layer for transactions.
	EndLayer      *uint32                `protobuf:"varint,2,opt,name=end_layer,json=endLayer,proto3,oneof" json:"end_layer,omitempty"`                                // Ending layer for transactions.
	Txid          [][]byte               `protobuf:"bytes,3,rep,name=txid,proto3" json:"txid,omitempty"`                                                               // Filter: specific transaction IDs to filter.
	Address       *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`                                                   // Filter by address (principal or recipient)
	Offset        uint64                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                                                          // Adjusts the starting point for data retrieval.
	Limit         uint64                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`                                                            // Specifies maximum number of items to fetch.
	IncludeState  bool                   `protobuf:"varint,8,opt,name=include_state,json=includeState,proto3" json:"include_state,omitempty"`                          // Whether to include transaction state in response.
	IncludeResult bool                   `protobuf:"varint,9,opt,name=include_result,json=includeResult,proto3" json:"include_result,omitempty"`                       // Whether to include result of transactions in response.
	SortOrder     SortOrder              `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3,enum=spacemesh.v2beta1.SortOrder" json:"sort_order,omitempty"` // specifies the sort order by layer (default is ASC)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionRequest) GetStartLayer() uint32 {
	if x != nil && x.StartLayer != nil {
		return *x.StartLayer
	}
	return 0
}

func (x *TransactionRequest) GetEndLayer() uint32 {
	if x != nil && x.EndLayer != nil {
		return *x.EndLayer
	}
	return 0
}

func (x *TransactionRequest) GetTxid() [][]byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *TransactionRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *TransactionRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TransactionRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransactionRequest) GetIncludeState() bool {
	if x != nil {
		return x.IncludeState
	}
	return false
}

func (x *TransactionRequest) GetIncludeResult() bool {
	if x != nil {
		return x.IncludeResult
	}
	return false
}

func (x *TransactionRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_ASC
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Transaction           `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`                                                                         // transaction
	TxResult      *TransactionResult     `protobuf:"bytes,2,opt,name=tx_result,json=txResult,proto3" json:"tx_result,omitempty"`                                             // optional transaction result
	TxState       *TransactionState      `protobuf:"varint,3,opt,name=tx_state,json=txState,proto3,enum=spacemesh.v2beta1.TransactionState,oneof" json:"tx_state,omitempty"` // optional transaction state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionResponse) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TransactionResponse) GetTxResult() *TransactionResult {
	if x != nil {
		return x.TxResult
	}
	return nil
}

func (x *TransactionResponse) GetTxState() TransactionState {
	if x != nil && x.TxState != nil {
		return *x.TxState
	}
	return TransactionState_TRANSACTION_STATE_UNSPECIFIED
}

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"` // list of transactions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionList) GetTransactions() []*TransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ParseTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // signed binary transaction
	Verify        bool                   `protobuf:"varint,2,opt,name=verify,proto3" json:"verify,omitempty"`          // if true signature verification will be executed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTransactionRequest) Reset() {
	*x = ParseTransactionRequest{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTransactionRequest) ProtoMessage() {}

func (x *ParseTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTransactionRequest.ProtoReflect.Descriptor instead.
func (*ParseTransactionRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{13}
}

func (x *ParseTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ParseTransactionRequest) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

type ParseTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tx            *Transaction           `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"` // parsed transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTransactionResponse) Reset() {
	*x = ParseTransactionResponse{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTransactionResponse) ProtoMessage() {}

func (x *ParseTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTransactionResponse.ProtoReflect.Descriptor instead.
func (*ParseTransactionResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{14}
}

func (x *ParseTransactionResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ParseTransactionResponse) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // signed binary transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TxId          []byte                 `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // transaction ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitTransactionResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SubmitTransactionResponse) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

type EstimateGasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // signed binary transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateGasRequest) Reset() {
	*x = EstimateGasRequest{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasRequest) ProtoMessage() {}

func (x *EstimateGasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasRequest.ProtoReflect.Descriptor instead.
func (*EstimateGasRequest) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{17}
}

func (x *EstimateGasRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type EstimateGasResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RecommendedMaxGas uint64                 `protobuf:"varint,2,opt,name=recommended_max_gas,json=recommendedMaxGas,proto3" json:"recommended_max_gas,omitempty"` // recommended max gas
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EstimateGasResponse) Reset() {
	*x = EstimateGasResponse{}
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasResponse) ProtoMessage() {}

func (x *EstimateGasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacemesh_v2beta1_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasResponse.ProtoReflect.Descriptor instead.
func (*EstimateGasResponse) Descriptor() ([]byte, []int) {
	return file_spacemesh_v2beta1_tx_proto_rawDescGZIP(), []int{18}
}

func (x *EstimateGasResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EstimateGasResponse) GetRecommendedMaxGas() uint64 {
	if x != nil {
		return x.RecommendedMaxGas
	}
	return 0
}

var File_spacemesh_v2beta1_tx_proto protoreflect.FileDescriptor

const file_spacemesh_v2beta1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1aspacemesh/v2beta1/tx.proto\x12\x11spacemesh.v2beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/rpc/status.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1fspacemesh/v2beta1/v2beta1.proto\"\x9f\x06\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x16\n" +
	"\x06method\x18\x04 \x01(\rR\x06method\x12.\n" +
	"\x05nonce\x18\x05 \x01(\v2\x18.spacemesh.v2beta1.NonceR\x05nonce\x12\x17\n" +
	"\amax_gas\x18\x06 \x01(\x04R\x06maxGas\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\x04R\bgasPrice\x12\x1b\n" +
	"\tmax_spend\x18\b \x01(\x04R\bmaxSpend\x12\x10\n" +
	"\x03raw\x18\t \x01(\fR\x03raw\x12B\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2..spacemesh.v2beta1.Transaction.TransactionTypeR\x04type\x12B\n" +
	"\bcontents\x18\v \x01(\v2&.spacemesh.v2beta1.TransactionContentsR\bcontents\"\x90\x03\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" TRANSACTION_TYPE_SINGLE_SIG_SEND\x10\x01\x12%\n" +
	"!TRANSACTION_TYPE_SINGLE_SIG_SPAWN\x10\x02\x12-\n" +
	"%TRANSACTION_TYPE_SINGLE_SIG_SELFSPAWN\x10\x03\x1a\x02\b\x01\x12#\n" +
	"\x1fTRANSACTION_TYPE_MULTI_SIG_SEND\x10\x04\x12$\n" +
	" TRANSACTION_TYPE_MULTI_SIG_SPAWN\x10\x05\x12,\n" +
	"$TRANSACTION_TYPE_MULTI_SIG_SELFSPAWN\x10\x06\x1a\x02\b\x01\x12\"\n" +
	"\x1eTRANSACTION_TYPE_VESTING_SPAWN\x10\a\x12 \n" +
	"\x1cTRANSACTION_TYPE_VAULT_SPAWN\x10\b\x12 \n" +
	"\x1cTRANSACTION_TYPE_DRAIN_VAULT\x10\t\"H\n" +
	"\fContentsSend\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"0\n" +
	"\x16ContentsSingleSigSpawn\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"K\n" +
	"\x15ContentsMultiSigSpawn\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\rR\brequired\x12\x16\n" +
	"\x06pubkey\x18\x02 \x03(\tR\x06pubkey\"\xc7\x01\n" +
	"\x12ContentsVaultSpawn\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x04R\vtotalAmount\x122\n" +
	"\x15initial_unlock_amount\x18\x03 \x01(\x04R\x13initialUnlockAmount\x12#\n" +
	"\rvesting_start\x18\x04 \x01(\rR\fvestingStart\x12\x1f\n" +
	"\vvesting_end\x18\x05 \x01(\rR\n" +
	"vestingEnd\"d\n" +
	"\x12ContentsDrainVault\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\xe8\x03\n" +
	"\x13TransactionContents\x125\n" +
	"\x04send\x18\x01 \x01(\v2\x1f.spacemesh.v2beta1.ContentsSendH\x00R\x04send\x12U\n" +
	"\x10single_sig_spawn\x18\x02 \x01(\v2).spacemesh.v2beta1.ContentsSingleSigSpawnH\x00R\x0esingleSigSpawn\x12R\n" +
	"\x0fmulti_sig_spawn\x18\x03 \x01(\v2(.spacemesh.v2beta1.ContentsMultiSigSpawnH\x00R\rmultiSigSpawn\x12O\n" +
	"\rvesting_spawn\x18\x04 \x01(\v2(.spacemesh.v2beta1.ContentsMultiSigSpawnH\x00R\fvestingSpawn\x12H\n" +
	"\vvault_spawn\x18\x05 \x01(\v2%.spacemesh.v2beta1.ContentsVaultSpawnH\x00R\n" +
	"vaultSpawn\x12H\n" +
	"\vdrain_vault\x18\x06 \x01(\v2%.spacemesh.v2beta1.ContentsDrainVaultH\x00R\n" +
	"drainVaultB\n" +
	"\n" +
	"\bcontents\"!\n" +
	"\x05Nonce\x12\x18\n" +
	"\acounter\x18\x01 \x01(\x04R\acounter\"\x8f\x03\n" +
	"\x11TransactionResult\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.spacemesh.v2beta1.TransactionResult.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fgas_consumed\x18\x03 \x01(\x04R\vgasConsumed\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x04R\x03fee\x12\x14\n" +
	"\x05block\x18\x05 \x01(\fR\x05block\x12\x14\n" +
	"\x05layer\x18\x06 \x01(\rR\x05layer\x12+\n" +
	"\x11touched_addresses\x18\a \x03(\tR\x10touchedAddresses\"\x8c\x01\n" +
	"\x06Status\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_SUCCESS\x10\x01\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_FAILURE\x10\x02\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_INVALID\x10\x03\"\xc6\x01\n" +
	"\x18TransactionStreamRequest\x12\x1f\n" +
	"\vstart_layer\x18\x01 \x01(\rR\n" +
	"startLayer\x12 \n" +
	"\tend_layer\x18\x02 \x01(\rH\x00R\bendLayer\x88\x01\x01\x12\x12\n" +
	"\x04txid\x18\x03 \x03(\fR\x04txid\x12!\n" +
	"\tprincipal\x18\x04 \x01(\tH\x01R\tprincipal\x88\x01\x01\x12\x14\n" +
	"\x05watch\x18\x05 \x01(\bR\x05watchB\f\n" +
	"\n" +
	"_end_layerB\f\n" +
	"\n" +
	"_principal\"\xf0\x02\n" +
	"\x12TransactionRequest\x12$\n" +
	"\vstart_layer\x18\x01 \x01(\rH\x00R\n" +
	"startLayer\x88\x01\x01\x12 \n" +
	"\tend_layer\x18\x02 \x01(\rH\x01R\bendLayer\x88\x01\x01\x12\x12\n" +
	"\x04txid\x18\x03 \x03(\fR\x04txid\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\a \x01(\x04R\x05limit\x12#\n" +
	"\rinclude_state\x18\b \x01(\bR\fincludeState\x12%\n" +
	"\x0einclude_result\x18\t \x01(\bR\rincludeResult\x12;\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x0e2\x1c.spacemesh.v2beta1.SortOrderR\tsortOrderB\x0e\n" +
	"\f_start_layerB\f\n" +
	"\n" +
	"_end_layerB\n" +
	"\n" +
	"\b_address\"\xda\x01\n" +
	"\x13TransactionResponse\x12.\n" +
	"\x02tx\x18\x01 \x01(\v2\x1e.spacemesh.v2beta1.TransactionR\x02tx\x12A\n" +
	"\ttx_result\x18\x02 \x01(\v2$.spacemesh.v2beta1.TransactionResultR\btxResult\x12C\n" +
	"\btx_state\x18\x03 \x01(\x0e2#.spacemesh.v2beta1.TransactionStateH\x00R\atxState\x88\x01\x01B\v\n" +
	"\t_tx_state\"]\n" +
	"\x0fTransactionList\x12J\n" +
	"\ftransactions\x18\x01 \x03(\v2&.spacemesh.v2beta1.TransactionResponseR\ftransactions\"S\n" +
	"\x17ParseTransactionRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\fR\vtransaction\x12\x16\n" +
	"\x06verify\x18\x02 \x01(\bR\x06verify\"v\n" +
	"\x18ParseTransactionResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12.\n" +
	"\x02tx\x18\x02 \x01(\v2\x1e.spacemesh.v2beta1.TransactionR\x02tx\"<\n" +
	"\x18SubmitTransactionRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\fR\vtransaction\"\\\n" +
	"\x19SubmitTransactionResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\fR\x04txId\"6\n" +
	"\x12EstimateGasRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\fR\vtransaction\"q\n" +
	"\x13EstimateGasResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12.\n" +
	"\x13recommended_max_gas\x18\x02 \x01(\x04R\x11recommendedMaxGas*\xa1\x02\n" +
	"\x10TransactionState\x12!\n" +
	"\x1dTRANSACTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATE_REJECTED\x10\x01\x12(\n" +
	"$TRANSACTION_STATE_INSUFFICIENT_FUNDS\x10\x02\x12!\n" +
	"\x1dTRANSACTION_STATE_CONFLICTING\x10\x03\x12\x1d\n" +
	"\x19TRANSACTION_STATE_MEMPOOL\x10\x04\x12\x1a\n" +
	"\x16TRANSACTION_STATE_MESH\x10\x05\x12\x1f\n" +
	"\x1bTRANSACTION_STATE_PROCESSED\x10\x06\x12!\n" +
	"\x1dTRANSACTION_STATE_INEFFECTUAL\x10\a2\x8d\x01\n" +
	"\x18TransactionStreamService\x12_\n" +
	"\x06Stream\x12+.spacemesh.v2beta1.TransactionStreamRequest\x1a&.spacemesh.v2beta1.TransactionResponse0\x01\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL2\xe8\x03\n" +
	"\x12TransactionService\x12\x85\x01\n" +
	"\x04List\x12%.spacemesh.v2beta1.TransactionRequest\x1a\".spacemesh.v2beta1.TransactionList\"2\x82\xd3\xe4\x93\x02,\x12*/spacemesh.v2beta1.TransactionService/List\x12k\n" +
	"\x10ParseTransaction\x12*.spacemesh.v2beta1.ParseTransactionRequest\x1a+.spacemesh.v2beta1.ParseTransactionResponse\x12n\n" +
	"\x11SubmitTransaction\x12+.spacemesh.v2beta1.SubmitTransactionRequest\x1a,.spacemesh.v2beta1.SubmitTransactionResponse\x12\\\n" +
	"\vEstimateGas\x12%.spacemesh.v2beta1.EstimateGasRequest\x1a&.spacemesh.v2beta1.EstimateGasResponse\x1a\x0f\xfa\xd2\xe4\x93\x02\t\x12\av2beta1B\xcf\x01\n" +
	"\x15com.spacemesh.v2beta1B\aTxProtoP\x01ZHgithub.com/spacemeshos/api/release/go/spacemesh/v2beta1;spacemeshv2beta1\xa2\x02\x03SXX\xaa\x02\x11Spacemesh.V2beta1\xca\x02\x11Spacemesh\\V2beta1\xe2\x02\x1dSpacemesh\\V2beta1\\GPBMetadata\xea\x02\x12Spacemesh::V2beta1b\x06proto3"

var (
	file_spacemesh_v2beta1_tx_proto_rawDescOnce sync.Once
	file_spacemesh_v2beta1_tx_proto_rawDescData []byte
)

func file_spacemesh_v2beta1_tx_proto_rawDescGZIP() []byte {
	file_spacemesh_v2beta1_tx_proto_rawDescOnce.Do(func() {
		file_spacemesh_v2beta1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacemesh_v2beta1_tx_proto_rawDesc), len(file_spacemesh_v2beta1_tx_proto_rawDesc)))
	})
	return file_spacemesh_v2beta1_tx_proto_rawDescData
}

var file_spacemesh_v2beta1_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacemesh_v2beta1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_spacemesh_v2beta1_tx_proto_goTypes = []any{
	(TransactionState)(0),             // 0: spacemesh.v2beta1.TransactionState
	(Transaction_TransactionType)(0),  // 1: spacemesh.v2beta1.Transaction.TransactionType
	(TransactionResult_Status)(0),     // 2: spacemesh.v2beta1.TransactionResult.Status
	(*Transaction)(nil),               // 3: spacemesh.v2beta1.Transaction
	(*ContentsSend)(nil),              // 4: spacemesh.v2beta1.ContentsSend
	(*ContentsSingleSigSpawn)(nil),    // 5: spacemesh.v2beta1.ContentsSingleSigSpawn
	(*ContentsMultiSigSpawn)(nil),     // 6: spacemesh.v2beta1.ContentsMultiSigSpawn
	(*ContentsVaultSpawn)(nil),        // 7: spacemesh.v2beta1.ContentsVaultSpawn
	(*ContentsDrainVault)(nil),        // 8: spacemesh.v2beta1.ContentsDrainVault
	(*TransactionContents)(nil),       // 9: spacemesh.v2beta1.TransactionContents
	(*Nonce)(nil),                     // 10: spacemesh.v2beta1.Nonce
	(*TransactionResult)(nil),         // 11: spacemesh.v2beta1.TransactionResult
	(*TransactionStreamRequest)(nil),  // 12: spacemesh.v2beta1.TransactionStreamRequest
	(*TransactionRequest)(nil),        // 13: spacemesh.v2beta1.TransactionRequest
	(*TransactionResponse)(nil),       // 14: spacemesh.v2beta1.TransactionResponse
	(*TransactionList)(nil),           // 15: spacemesh.v2beta1.TransactionList
	(*ParseTransactionRequest)(nil),   // 16: spacemesh.v2beta1.ParseTransactionRequest
	(*ParseTransactionResponse)(nil),  // 17: spacemesh.v2beta1.ParseTransactionResponse
	(*SubmitTransactionRequest)(nil),  // 18: spacemesh.v2beta1.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil), // 19: spacemesh.v2beta1.SubmitTransactionResponse
	(*EstimateGasRequest)(nil),        // 20: spacemesh.v2beta1.EstimateGasRequest
	(*EstimateGasResponse)(nil),       // 21: spacemesh.v2beta1.EstimateGasResponse
	(SortOrder)(0),                    // 22: spacemesh.v2beta1.SortOrder
	(*status.Status)(nil),             // 23: google.rpc.Status
}
var file_spacemesh_v2beta1_tx_proto_depIdxs = []int32{
	10, // 0: spacemesh.v2beta1.Transaction.nonce:type_name -> spacemesh.v2beta1.Nonce
	1,  // 1: spacemesh.v2beta1.Transaction.type:type_name -> spacemesh.v2beta1.Transaction.TransactionType
	9,  // 2: spacemesh.v2beta1.Transaction.contents:type_name -> spacemesh.v2beta1.TransactionContents
	4,  // 3: spacemesh.v2beta1.TransactionContents.send:type_name -> spacemesh.v2beta1.ContentsSend
	5,  // 4: spacemesh.v2beta1.TransactionContents.single_sig_spawn:type_name -> spacemesh.v2beta1.ContentsSingleSigSpawn
	6,  // 5: spacemesh.v2beta1.TransactionContents.multi_sig_spawn:type_name -> spacemesh.v2beta1.ContentsMultiSigSpawn
	6,  // 6: spacemesh.v2beta1.TransactionContents.vesting_spawn:type_name -> spacemesh.v2beta1.ContentsMultiSigSpawn
	7,  // 7: spacemesh.v2beta1.TransactionContents.vault_spawn:type_name -> spacemesh.v2beta1.ContentsVaultSpawn
	8,  // 8: spacemesh.v2beta1.TransactionContents.drain_vault:type_name -> spacemesh.v2beta1.ContentsDrainVault
	2,  // 9: spacemesh.v2beta1.TransactionResult.status:type_name -> spacemesh.v2beta1.TransactionResult.Status
	22, // 10: spacemesh.v2beta1.TransactionRequest.sort_order:type_name -> spacemesh.v2beta1.SortOrder
	3,  // 11: spacemesh.v2beta1.TransactionResponse.tx:type_name -> spacemesh.v2beta1.Transaction
	11, // 12: spacemesh.v2beta1.TransactionResponse.tx_result:type_name -> spacemesh.v2beta1.TransactionResult
	0,  // 13: spacemesh.v2beta1.TransactionResponse.tx_state:type_name -> spacemesh.v2beta1.TransactionState
	14, // 14: spacemesh.v2beta1.TransactionList.transactions:type_name -> spacemesh.v2beta1.TransactionResponse
	23, // 15: spacemesh.v2beta1.ParseTransactionResponse.status:type_name -> google.rpc.Status
	3,  // 16: spacemesh.v2beta1.ParseTransactionResponse.tx:type_name -> spacemesh.v2beta1.Transaction
	23, // 17: spacemesh.v2beta1.SubmitTransactionResponse.status:type_name -> google.rpc.Status
	23, // 18: spacemesh.v2beta1.EstimateGasResponse.status:type_name -> google.rpc.Status
	12, // 19: spacemesh.v2beta1.TransactionStreamService.Stream:input_type -> spacemesh.v2beta1.TransactionStreamRequest
	13, // 20: spacemesh.v2beta1.TransactionService.List:input_type -> spacemesh.v2beta1.TransactionRequest
	16, // 21: spacemesh.v2beta1.TransactionService.ParseTransaction:input_type -> spacemesh.v2beta1.ParseTransactionRequest
	18, // 22: spacemesh.v2beta1.TransactionService.SubmitTransaction:input_type -> spacemesh.v2beta1.SubmitTransactionRequest
	20, // 23: spacemesh.v2beta1.TransactionService.EstimateGas:input_type -> spacemesh.v2beta1.EstimateGasRequest
	14, // 24: spacemesh.v2beta1.TransactionStreamService.Stream:output_type -> spacemesh.v2beta1.TransactionResponse
	15, // 25: spacemesh.v2beta1.TransactionService.List:output_type -> spacemesh.v2beta1.TransactionList
	17, // 26: spacemesh.v2beta1.TransactionService.ParseTransaction:output_type -> spacemesh.v2beta1.ParseTransactionResponse
	19, // 27: spacemesh.v2beta1.TransactionService.SubmitTransaction:output_type -> spacemesh.v2beta1.SubmitTransactionResponse
	21, // 28: spacemesh.v2beta1.TransactionService.EstimateGas:output_type -> spacemesh.v2beta1.EstimateGasResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_spacemesh_v2beta1_tx_proto_init() }
func file_spacemesh_v2beta1_tx_proto_init() {
	if File_spacemesh_v2beta1_tx_proto != nil {
		return
	}
	file_spacemesh_v2beta1_v2beta1_proto_init()
	file_spacemesh_v2beta1_tx_proto_msgTypes[6].OneofWrappers = []any{
		(*TransactionContents_Send)(nil),
		(*TransactionContents_SingleSigSpawn)(nil),
		(*TransactionContents_MultiSigSpawn)(nil),
		(*TransactionContents_VestingSpawn)(nil),
		(*TransactionContents_VaultSpawn)(nil),
		(*TransactionContents_DrainVault)(nil),
	}
	file_spacemesh_v2beta1_tx_proto_msgTypes[9].OneofWrappers = []any{}
	file_spacemesh_v2beta1_tx_proto_msgTypes[10].OneofWrappers = []any{}
	file_spacemesh_v2beta1_tx_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacemesh_v2beta1_tx_proto_rawDesc), len(file_spacemesh_v2beta1_tx_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_spacemesh_v2beta1_tx_proto_goTypes,
		DependencyIndexes: file_spacemesh_v2beta1_tx_proto_depIdxs,
		EnumInfos:         file_spacemesh_v2beta1_tx_proto_enumTypes,
		MessageInfos:      file_spacemesh_v2beta1_tx_proto_msgTypes,
	}.Build()
	File_spacemesh_v2beta1_tx_proto = out.File
	file_spacemesh_v2beta1_tx_proto_goTypes = nil
	file_spacemesh_v2beta1_tx_proto_depIdxs = nil
}
