name: Build and Push Swagger-UI to R2 mainnet-api-docs.spacemesh.network

on:
  push:
    branches:
      - fix-sync-with-go-sm
    paths:
      - 'release/openapi/swagger/src/**'

jobs:
  check-version:
    runs-on: ubuntu-22.04
    outputs:
      go-sm-release: ${{ steps.go-sm-release.outputs.GO_SM_RELEASE_VER }}
      go-sm-api-version: ${{ steps.go-sm-api-version.outputs.GO_SM_API_VERSION }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: spacemeshos/go-spacemesh
        fetch-depth: 0
    - name: Get current go-sm release tag
      id: go-sm-release
      run: |
        version=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "GO_SM_RELEASE_VER=$version" > $GITHUB_OUTPUT
    
    - name: Checkout target repository on last release
      uses: actions/checkout@v4
      with:
        repository: spacemeshos/go-spacemesh
        path: go-spacemesh
        fetch-depth: 0
        ref: 'refs/tags/${{ steps.go-sm-release.outputs.GO_SM_RELEASE_VER }}'
    
    - name: Extract dependency version
      id: go-sm-api-version
      run: |
        version=$(grep -E 'github.com/spacemeshos/api/release/go' gomodtest/go.mod | awk '{print $2}')
        echo "$version"
        echo "GO_SM_API_VERSION=$version" > $GITHUB_OUTPUT

  build-deploy:
    runs-on: ubuntu-22.04
    needs: check-version
    steps:
    - name: Print versions
      run: |
        echo "API version on go-sm: ${{ needs.check-version.outputs.go-sm-api-version }}"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'refs/tags/${{ needs.check-version.outputs.go-sm-api-version }}'
    - name: Use Node.js v20.14.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'

    - name: npm install
      run: npm install
      working-directory: release/openapi/swagger

    - name: npm build
      run: npm run build
      working-directory: release/openapi/swagger

    - uses: actions/upload-artifact@v4
      with:
        name: swagger-ui-build
        path: release/openapi/swagger/dist

    - name: upload to mainnet
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
          AWS_S3_BUCKET: ${{ secrets.CLOUDFLARE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          SOURCE_DIR: release/openapi/swagger/dist
          DEST_DIR: ''
          AWS_S3_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com

    - name: upload to testnet
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
          AWS_S3_BUCKET: ${{ secrets.CLOUDFLARE_TESTNET_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          SOURCE_DIR: release/openapi/swagger/dist
          DEST_DIR: ''
          AWS_S3_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
   